// Dictionary mapping name IDs to their details
export default {
  1: {
    id: 1,
    arabicName: "هو",
    englishName: "Huwa",
    englishMean: "He",
    timestamp1: 22,
  },
  2: {
    id: 2,
    arabicName: "الله",
    englishName: "Allah",
    englishMean: "God",
    timestamp1: 22.5,
  },
  3: {
    id: 3,
    arabicName: "الذي",
    englishName: "Alladhi",
    englishMean: "The One Who",
    timestamp1: 23.5,
  },
  4: {
    id: 4,
    arabicName: "لا",
    englishName: "Ella",
    englishMean: "No / Not",
    timestamp1: 24.5,
  },
  5: {
    id: 5,
    arabicName: "إله",
    englishName: "Elah",
    englishMean: "God / Deity",
    timestamp1: 25,
  },
  6: {
    id: 6,
    arabicName: "إلا",
    englishName: "Ella",
    englishMean: "Except",
    timestamp1: 26,
  },
  7: {
    id: 7,
    arabicName: "هو",
    englishName: "Huwa",
    englishMean: "He",
    timestamp1: 26.5,
  },
  13: {
    id: 13,
    rank: 1,
    englishName: "Ar-Rahman",
    englishMean: "The Most Merciful",
    arabicName: "ٱلرَّحْمَٰنُ",
    frequency: 45,
    timestamp1: 29,
    descAr:
      "رحمةُ اللهِ الشاملةُ التي يُظهرُها لجميعِ خلقِه دونَ استثناء، بخلقِهم ورزقِهم.",
    descEn:
      "Allah’s comprehensive mercy which He shows to all His creation without exception by creating them and providing for them",
    pronounciation: "ar-rah-MAAN",
    quran_hadith: "Quran",
    reference: [
      { surah: 1, ayah: 1 },
      { surah: 1, ayah: 3 },
      { surah: 2, ayah: 163 },
      { surah: 17, ayah: 110 },
      { surah: 19, ayah: 45 },
      { surah: 19, ayah: 58 },
      { surah: 19, ayah: 61 },
      { surah: 19, ayah: 69 },
      { surah: 19, ayah: 75 },
      { surah: 19, ayah: 78 },
      { surah: 19, ayah: 85 },
      { surah: 19, ayah: 87 },
      { surah: 19, ayah: 88 },
      { surah: 19, ayah: 93 },
      { surah: 19, ayah: 96 },
      { surah: 20, ayah: 5 },
      { surah: 20, ayah: 90 },
      { surah: 20, ayah: 109 },
      { surah: 21, ayah: 26 },
      { surah: 21, ayah: 36 },
      { surah: 21, ayah: 42 },
      { surah: 21, ayah: 112 },
      { surah: 25, ayah: 59 },
      { surah: 25, ayah: 60 },
      { surah: 25, ayah: 63 },
      { surah: 26, ayah: 5 },
      { surah: 27, ayah: 30 },
      { surah: 36, ayah: 11 },
      { surah: 36, ayah: 15 },
      { surah: 36, ayah: 23 },
      { surah: 36, ayah: 52 },
      { surah: 41, ayah: 2 },
      { surah: 43, ayah: 19 },
      { surah: 43, ayah: 20 },
      { surah: 43, ayah: 36 },
      { surah: 43, ayah: 45 },
      { surah: 50, ayah: 33 },
      { surah: 55, ayah: 1 },
      { surah: 59, ayah: 22 },
      { surah: 67, ayah: 3 },
      { surah: 67, ayah: 19 },
      { surah: 67, ayah: 20 },
      { surah: 67, ayah: 29 },
      { surah: 78, ayah: 37 },
      { surah: 78, ayah: 38 },
    ],
  },
  12: {
    id: 12,
    rank: 2,
    englishName: "Ar-Raheem",
    englishMean: "The Most Compassionate",
    arabicName: "ٱلرَّحِيمُ",
    frequency: 34,
    timestamp1: 30,
    descAr: "",
    descEn: "",
    pronounciation: "ar-ra-HEEM",
    quran_hadith: "Quran",
    reference: [
      { surah: 1, ayah: 1 },
      { surah: 1, ayah: 3 },
      { surah: 2, ayah: 37 },
      { surah: 2, ayah: 54 },
      { surah: 2, ayah: 128 },
      { surah: 2, ayah: 160 },
      { surah: 2, ayah: 163 },
      { surah: 9, ayah: 104 },
      { surah: 9, ayah: 118 },
      { surah: 10, ayah: 107 },
      { surah: 12, ayah: 98 },
      { surah: 15, ayah: 49 },
      { surah: 26, ayah: 9 },
      { surah: 26, ayah: 68 },
      { surah: 26, ayah: 104 },
      { surah: 26, ayah: 122 },
      { surah: 26, ayah: 140 },
      { surah: 26, ayah: 159 },
      { surah: 26, ayah: 175 },
      { surah: 26, ayah: 191 },
      { surah: 26, ayah: 217 },
      { surah: 27, ayah: 30 },
      { surah: 28, ayah: 16 },
      { surah: 30, ayah: 5 },
      { surah: 32, ayah: 6 },
      { surah: 34, ayah: 2 },
      { surah: 36, ayah: 5 },
      { surah: 39, ayah: 53 },
      { surah: 41, ayah: 2 },
      { surah: 42, ayah: 5 },
      { surah: 44, ayah: 42 },
      { surah: 46, ayah: 8 },
      { surah: 52, ayah: 28 },
      { surah: 59, ayah: 22 },
    ],
  },
  8: {
    id: 8,
    rank: 3,
    englishName: "Al-Malik",
    englishMean: "The King",
    arabicName: "ٱلْمَلِكُ",
    frequency: 28,
    timestamp1: 32,
    descAr: "",
    descEn: "",
    pronounciation: "al-ma-LEEK",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 247 },
      { surah: 2, ayah: 251 },
      { surah: 2, ayah: 258 },
      { surah: 3, ayah: 26 },
      { surah: 4, ayah: 53 },
      { surah: 6, ayah: 73 },
      { surah: 12, ayah: 43 },
      { surah: 12, ayah: 50 },
      { surah: 12, ayah: 54 },
      { surah: 12, ayah: 72 },
      { surah: 12, ayah: 76 },
      { surah: 12, ayah: 101 },
      { surah: 17, ayah: 111 },
      { surah: 20, ayah: 114 },
      { surah: 22, ayah: 56 },
      { surah: 23, ayah: 116 },
      { surah: 25, ayah: 2 },
      { surah: 25, ayah: 26 },
      { surah: 35, ayah: 13 },
      { surah: 39, ayah: 6 },
      { surah: 40, ayah: 16 },
      { surah: 40, ayah: 29 },
      { surah: 59, ayah: 23 },
      { surah: 62, ayah: 1 },
      { surah: 64, ayah: 1 },
      { surah: 67, ayah: 1 },
    ],
  },
  11: {
    id: 11,
    rank: 4,
    englishName: "Al-Quddus",
    englishMean: "The Most Holy",
    arabicName: "ٱلْقُدُّوسُ",
    frequency: 2,
    timestamp1: 33,
    descAr: "",
    descEn: "",
    pronounciation: "al-qud-DOOS",
    quran_hadith: "Quran",
    reference: [
      { surah: 59, ayah: 23 },
      { surah: 62, ayah: 1 },
    ],
  },
  10: {
    id: 10,
    rank: 5,
    englishName: "As-Salam",
    englishMean: "The Source of Peace",
    arabicName: "ٱلسَّلَامُ",
    frequency: 1,
    timestamp1: 34,
    descAr: "",
    descEn: "",
    pronounciation: "as-sa-LAAM",
    quran_hadith: "Quran",
    reference: [{ surah: 59, ayah: 23 }],
  },
  9: {
    id: 9,
    rank: 6,
    englishName: "Al-Mu'min",
    englishMean: "The Giver of Security",
    arabicName: "ٱلْمُؤْمِنُ",
    frequency: 1,
    timestamp1: 35.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-mu'-MIN",
    quran_hadith: "Quran",
    reference: [{ surah: 59, ayah: 23 }],
  },
  18: {
    id: 18,
    rank: 7,
    englishName: "Al-Muhaymin",
    englishMean: "The Guardian",
    arabicName: "ٱلْمُهَيْمِنُ",
    frequency: 1,
    timestamp1: 36.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-mu-HAY-min",
    quran_hadith: "Quran",
    reference: [{ surah: 59, ayah: 23 }],
  },
  19: {
    id: 19,
    rank: 8,
    englishName: "Al-'Aziz",
    englishMean: "The Almighty",
    arabicName: "ٱلْعَزِيزُ",
    frequency: 64,
    timestamp1: 38,
    descAr: "",
    descEn: "",
    pronounciation: "al-a-ZEEZ",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 129 },
      { surah: 3, ayah: 6 },
      { surah: 3, ayah: 18 },
      { surah: 3, ayah: 62 },
      { surah: 3, ayah: 126 },
      { surah: 5, ayah: 118 },
      { surah: 6, ayah: 96 },
      { surah: 11, ayah: 66 },
      { surah: 12, ayah: 30 },
      { surah: 12, ayah: 51 },
      { surah: 12, ayah: 78 },
      { surah: 12, ayah: 88 },
      { surah: 14, ayah: 1 },
      { surah: 14, ayah: 4 },
      { surah: 16, ayah: 60 },
      { surah: 26, ayah: 9 },
      { surah: 26, ayah: 68 },
      { surah: 26, ayah: 104 },
      { surah: 26, ayah: 122 },
      { surah: 26, ayah: 140 },
      { surah: 26, ayah: 159 },
      { surah: 26, ayah: 175 },
      { surah: 26, ayah: 191 },
      { surah: 26, ayah: 217 },
      { surah: 27, ayah: 9 },
      { surah: 27, ayah: 78 },
      { surah: 29, ayah: 26 },
      { surah: 29, ayah: 42 },
      { surah: 30, ayah: 5 },
      { surah: 30, ayah: 27 },
      { surah: 31, ayah: 9 },
      { surah: 32, ayah: 6 },
      { surah: 34, ayah: 6 },
      { surah: 34, ayah: 27 },
      { surah: 35, ayah: 2 },
      { surah: 36, ayah: 5 },
      { surah: 36, ayah: 38 },
      { surah: 38, ayah: 9 },
      { surah: 38, ayah: 66 },
      { surah: 39, ayah: 1 },
      { surah: 39, ayah: 5 },
      { surah: 40, ayah: 2 },
      { surah: 40, ayah: 8 },
      { surah: 40, ayah: 42 },
      { surah: 41, ayah: 12 },
      { surah: 42, ayah: 3 },
      { surah: 42, ayah: 19 },
      { surah: 43, ayah: 9 },
      { surah: 44, ayah: 42 },
      { surah: 44, ayah: 49 },
      { surah: 45, ayah: 2 },
      { surah: 45, ayah: 37 },
      { surah: 46, ayah: 2 },
      { surah: 57, ayah: 1 },
      { surah: 59, ayah: 1 },
      { surah: 59, ayah: 23 },
      { surah: 59, ayah: 24 },
      { surah: 60, ayah: 5 },
      { surah: 61, ayah: 1 },
      { surah: 62, ayah: 1 },
      { surah: 62, ayah: 3 },
      { surah: 64, ayah: 18 },
      { surah: 67, ayah: 2 },
      { surah: 85, ayah: 8 },
    ],
  },
  14: {
    id: 14,
    rank: 9,
    englishName: "Al-Jabbar",
    englishMean: "The Compeller",
    arabicName: "ٱلْجَبَّارُ",
    frequency: 1,
    timestamp1: 39,
    descAr: "",
    descEn: "",
    pronounciation: "al-jab-BAAR",
    quran_hadith: "Quran",
    reference: [{ surah: 59, ayah: 23 }],
  },
  15: {
    id: 15,
    rank: 10,
    englishName: "Al-Mutakabbir",
    englishMean: "The Supreme",
    arabicName: "ٱلْمُتَكَبِّرُ",
    frequency: 1,
    timestamp1: 40.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-mu-ta-KAB-bir",
    quran_hadith: "Quran",
    reference: [{ surah: 59, ayah: 23 }],
  },
  16: {
    id: 16,
    rank: 11,
    englishName: "Al-Khaliq",
    englishMean: "The Creator",
    arabicName: "ٱلْخَالِقُ",
    frequency: 3,
    timestamp1: 43,
    descAr: "",
    descEn: "",
    pronounciation: "al-KHA-liq",
    quran_hadith: "Quran",
    reference: [
      { surah: 15, ayah: 86 },
      { surah: 36, ayah: 81 },
      { surah: 59, ayah: 24 },
    ],
  },
  17: {
    id: 17,
    rank: 12,
    englishName: "Al-Bari'",
    englishMean: "The Maker",
    arabicName: "ٱلْبَارِئُ",
    frequency: 1,
    timestamp1: 45,
    descAr: "",
    descEn: "",
    pronounciation: "al-BA-ri",
    quran_hadith: "Quran",
    reference: [{ surah: 59, ayah: 24 }],
  },
  27: {
    id: 27,
    rank: 13,
    englishName: "Al-Musawwir",
    englishMean: "The Fashioner",
    arabicName: "ٱلْمُصَوِّرُ",
    frequency: 1,
    timestamp1: 48,
    descAr: "",
    descEn: "",
    pronounciation: "al-mu-SAW-wir",
    quran_hadith: "Quran",
    reference: [{ surah: 59, ayah: 24 }],
  },
  64: {
    id: 64,
    rank: 14,
    englishName: "Al-Ghaffar",
    englishMean: "The Oft-Forgiving",
    arabicName: "ٱلْغَفَّارُ",
    frequency: 3,
    timestamp1: 49,
    descAr: "",
    descEn: "",
    pronounciation: "al-ghaf-FAR",
    quran_hadith: "Quran",
    reference: [
      { surah: 38, ayah: 66 },
      { surah: 39, ayah: 5 },
      { surah: 40, ayah: 42 },
    ],
  },
  65: {
    id: 65,
    rank: 15,
    englishName: "Al-Qahhar",
    englishMean: "The Subduer",
    arabicName: "ٱلْقَهَّارُ",
    frequency: 6,
    timestamp1: 50,
    descAr: "",
    descEn: "",
    pronounciation: "al-qah-HAR",
    quran_hadith: "Quran",
    reference: [
      { surah: 12, ayah: 39 },
      { surah: 13, ayah: 16 },
      { surah: 14, ayah: 48 },
      { surah: 38, ayah: 65 },
      { surah: 39, ayah: 4 },
      { surah: 40, ayah: 16 },
    ],
  },
  58: {
    id: 58,
    rank: 16,
    englishName: "Al-Wahhab",
    englishMean: "The Bestower",
    arabicName: "ٱلْوَهَّابُ",
    frequency: 3,
    timestamp1: 51,
    descAr: "",
    descEn: "",
    pronounciation: "al-wah-HAB",
    quran_hadith: "Quran",
    reference: [
      { surah: 3, ayah: 8 },
      { surah: 38, ayah: 9 },
      { surah: 38, ayah: 35 },
    ],
  },
  66: {
    id: 66,
    rank: 17,
    englishName: "Ar-Razzaq",
    englishMean: "The Provider",
    arabicName: "ٱلرَّزَّاقُ",
    frequency: 1,
    timestamp1: 52,
    descAr: "",
    descEn: "",
    pronounciation: "ar-raz-ZAQ",
    quran_hadith: "Quran",
    reference: [{ surah: 51, ayah: 58 }],
  },
  67: {
    id: 67,
    rank: 18,
    englishName: "Al-Fattah",
    englishMean: "The Opener",
    arabicName: "ٱلْفَتَّاحُ",
    frequency: 1,
    timestamp1: 54,
    descAr: "",
    descEn: "",
    pronounciation: "al-fat-TAH",
    quran_hadith: "Quran",
    reference: [{ surah: 34, ayah: 26 }],
  },
  63: {
    id: 63,
    rank: 19,
    englishName: "Al-'Alim",
    englishMean: "The All-Knowing",
    arabicName: "ٱلْعَلِيمُ",
    frequency: 32,
    timestamp1: 55,
    descAr: "",
    descEn: "",
    pronounciation: "al-a-LEEM",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 32 },
      { surah: 2, ayah: 127 },
      { surah: 2, ayah: 137 },
      { surah: 3, ayah: 35 },
      { surah: 5, ayah: 76 },
      { surah: 6, ayah: 13 },
      { surah: 6, ayah: 96 },
      { surah: 6, ayah: 115 },
      { surah: 8, ayah: 61 },
      { surah: 10, ayah: 65 },
      { surah: 12, ayah: 34 },
      { surah: 12, ayah: 83 },
      { surah: 12, ayah: 100 },
      { surah: 15, ayah: 86 },
      { surah: 21, ayah: 4 },
      { surah: 26, ayah: 220 },
      { surah: 27, ayah: 78 },
      { surah: 29, ayah: 5 },
      { surah: 29, ayah: 60 },
      { surah: 30, ayah: 54 },
      { surah: 34, ayah: 26 },
      { surah: 36, ayah: 38 },
      { surah: 36, ayah: 81 },
      { surah: 40, ayah: 2 },
      { surah: 41, ayah: 12 },
      { surah: 41, ayah: 36 },
      { surah: 43, ayah: 9 },
      { surah: 43, ayah: 84 },
      { surah: 44, ayah: 6 },
      { surah: 51, ayah: 30 },
      { surah: 66, ayah: 2 },
      { surah: 66, ayah: 3 },
    ],
  },
  28: {
    id: 28,
    rank: 20,
    englishName: "Al-Qabid",
    englishMean: "The Withholder",
    arabicName: "ٱلْقَابِضُ",
    frequency: null,
    timestamp1: 56,
    descAr: "",
    descEn: "",
    pronounciation: "al-QA-bid",
    quran_hadith: "Hadith",
    reference: [{ surah: 2, ayah: 245 }],
  },
  29: {
    id: 29,
    rank: 21,
    englishName: "Al-Basit",
    englishMean: "The Extender",
    arabicName: "ٱلْبَاسِطُ",
    frequency: 0,
    timestamp1: 57,
    descAr: "",
    descEn: "",
    pronounciation: "al-BA-sit",
    quran_hadith: "Hadith",
  },
  57: {
    id: 57,
    rank: 22,
    englishName: "Al-Khafid",
    englishMean: "The Abaser",
    arabicName: "ٱلْخَافِضُ",
    frequency: 0,
    timestamp1: 58.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-KHA-fid",
    quran_hadith: "Hadith",
  },
  59: {
    id: 59,
    rank: 23,
    englishName: "Ar-Rafi'",
    englishMean: "The Exalter",
    arabicName: "ٱلرَّافِعُ",
    frequency: 0,
    timestamp1: 60,
    descAr: "",
    descEn: "",
    pronounciation: "ar-ra-FEE",
    quran_hadith: "Hadith",
  },
  60: {
    id: 60,
    rank: 24,
    englishName: "Al-Mu'izz",
    englishMean: "The Honorer",
    arabicName: "ٱلْمُعِزُّ",
    frequency: 1,
    timestamp1: 61,
    descAr: "",
    descEn: "",
    pronounciation: "al-mu-IZZ",
    quran_hadith: "Quran",
    reference: [{ surah: 6, ayah: 143 }],
  },
  46: {
    id: 46,
    rank: 25,
    englishName: "Al-Mudhill",
    englishMean: "The Humiliator",
    arabicName: "ٱلْمُذِلُّ",
    frequency: 0,
    timestamp1: 62,
    descAr: "",
    descEn: "",
    pronounciation: "al-mu-DHILL",
    quran_hadith: "Hadith",
  },
  45: {
    id: 45,
    rank: 26,
    englishName: "As-Sami'",
    englishMean: "The All-Hearing",
    arabicName: "ٱلسَّمِيعُ",
    frequency: 19,
    timestamp1: 63.5,
    descAr: "",
    descEn: "",
    pronounciation: "as-sa-MEE",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 127 },
      { surah: 2, ayah: 137 },
      { surah: 3, ayah: 35 },
      { surah: 5, ayah: 76 },
      { surah: 6, ayah: 13 },
      { surah: 6, ayah: 115 },
      { surah: 8, ayah: 61 },
      { surah: 10, ayah: 65 },
      { surah: 12, ayah: 34 },
      { surah: 17, ayah: 1 },
      { surah: 21, ayah: 4 },
      { surah: 26, ayah: 220 },
      { surah: 29, ayah: 5 },
      { surah: 29, ayah: 60 },
      { surah: 40, ayah: 20 },
      { surah: 40, ayah: 56 },
      { surah: 41, ayah: 36 },
      { surah: 42, ayah: 11 },
      { surah: 44, ayah: 6 },
    ],
  },
  43: {
    id: 43,
    rank: 27,
    englishName: "Al-Basir",
    englishMean: "The All-Seeing",
    arabicName: "ٱلْبَصِيرُ",
    frequency: 4,
    timestamp1: 65,
    descAr: "",
    descEn: "",
    pronounciation: "al-ba-SEER",
    quran_hadith: "Quran",
    reference: [
      { surah: 17, ayah: 1 },
      { surah: 40, ayah: 20 },
      { surah: 40, ayah: 56 },
      { surah: 42, ayah: 11 },
    ],
  },
  25: {
    id: 25,
    rank: 28,
    englishName: "Al-Hakam",
    englishMean: "The Judge",
    arabicName: "ٱلْحَكَمُ",
    frequency: 7,
    timestamp1: 66,
    descAr: "",
    descEn: "",
    pronounciation: "al-HA-kam",
    quran_hadith: "Quran",
    reference: [
      { surah: 6, ayah: 57 },
      { surah: 6, ayah: 62 },
      { surah: 12, ayah: 40 },
      { surah: 12, ayah: 67 },
      { surah: 19, ayah: 12 },
      { surah: 28, ayah: 70 },
      { surah: 28, ayah: 88 },
    ],
  },
  26: {
    id: 26,
    rank: 29,
    englishName: "Al-'Adl",
    englishMean: "The Just",
    arabicName: "ٱلْعَدْلُ",
    frequency: 0,
    timestamp1: 67,
    descAr: "",
    descEn: "",
    pronounciation: "al-ADL",
    quran_hadith: "Hadith",
  },
  61: {
    id: 61,
    rank: 30,
    englishName: "Al-Latif",
    englishMean: "The Subtle",
    arabicName: "ٱللَّطِيفُ",
    frequency: 2,
    timestamp1: 68,
    descAr: "",
    descEn: "",
    pronounciation: "al-la-TEEF",
    quran_hadith: "Quran",
    reference: [
      { surah: 6, ayah: 103 },
      { surah: 67, ayah: 14 },
    ],
  },
  47: {
    id: 47,
    rank: 31,
    englishName: "Al-Khabir",
    englishMean: "The All-Aware",
    arabicName: "ٱلْخَبِيرُ",
    frequency: 6,
    timestamp1: 69.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-kha-BEER",
    quran_hadith: "Quran",
    reference: [
      { surah: 6, ayah: 18 },
      { surah: 6, ayah: 73 },
      { surah: 6, ayah: 103 },
      { surah: 34, ayah: 1 },
      { surah: 66, ayah: 3 },
      { surah: 67, ayah: 14 },
    ],
  },
  56: {
    id: 56,
    rank: 32,
    englishName: "Al-Halim",
    englishMean: "The Forbearing",
    arabicName: "ٱلْحَلِيمُ",
    frequency: 1,
    timestamp1: 70.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-ha-LEEM",
    quran_hadith: "Quran",
    reference: [{ surah: 11, ayah: 87 }],
  },
  44: {
    id: 44,
    rank: 33,
    englishName: "Al-'Azim",
    englishMean: "The Magnificent",
    arabicName: "ٱلْعَظِيمُ",
    frequency: 36,
    timestamp1: 72,
    descAr: "",
    descEn: "",
    pronounciation: "al-a-ZHEEM",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 105 },
      { surah: 2, ayah: 255 },
      { surah: 3, ayah: 74 },
      { surah: 4, ayah: 13 },
      { surah: 5, ayah: 119 },
      { surah: 8, ayah: 29 },
      { surah: 9, ayah: 63 },
      { surah: 9, ayah: 72 },
      { surah: 9, ayah: 89 },
      { surah: 9, ayah: 100 },
      { surah: 9, ayah: 111 },
      { surah: 9, ayah: 129 },
      { surah: 10, ayah: 64 },
      { surah: 15, ayah: 87 },
      { surah: 21, ayah: 76 },
      { surah: 23, ayah: 86 },
      { surah: 26, ayah: 63 },
      { surah: 27, ayah: 26 },
      { surah: 37, ayah: 60 },
      { surah: 37, ayah: 76 },
      { surah: 37, ayah: 115 },
      { surah: 40, ayah: 9 },
      { surah: 42, ayah: 4 },
      { surah: 44, ayah: 57 },
      { surah: 56, ayah: 46 },
      { surah: 56, ayah: 74 },
      { surah: 56, ayah: 96 },
      { surah: 57, ayah: 12 },
      { surah: 57, ayah: 21 },
      { surah: 57, ayah: 29 },
      { surah: 61, ayah: 12 },
      { surah: 62, ayah: 4 },
      { surah: 64, ayah: 9 },
      { surah: 69, ayah: 33 },
      { surah: 69, ayah: 52 },
      { surah: 78, ayah: 2 },
    ],
  },
  42: {
    id: 42,
    rank: 34,
    englishName: "Al-Ghafur",
    englishMean: "The Forgiving",
    arabicName: "ٱلْغَفُورُ",
    frequency: 11,
    timestamp1: 73.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-gha-FOOR",
    quran_hadith: "Quran",
    reference: [
      { surah: 10, ayah: 107 },
      { surah: 12, ayah: 98 },
      { surah: 15, ayah: 49 },
      { surah: 18, ayah: 58 },
      { surah: 28, ayah: 16 },
      { surah: 34, ayah: 2 },
      { surah: 39, ayah: 53 },
      { surah: 42, ayah: 5 },
      { surah: 46, ayah: 8 },
      { surah: 67, ayah: 2 },
      { surah: 85, ayah: 14 },
    ],
  },
  62: {
    id: 62,
    rank: 35,
    englishName: "Ash-Shakur",
    englishMean: "The Appreciative",
    arabicName: "ٱلشَّكُورُ",
    frequency: 1,
    timestamp1: 75,
    descAr: "",
    descEn: "",
    pronounciation: "ash-sha-KOOR",
    quran_hadith: "Quran",
    reference: [{ surah: 34, ayah: 13 }],
  },
  35: {
    id: 35,
    rank: 36,
    englishName: "Al-'Aliyy",
    englishMean: "The Most High",
    arabicName: "ٱلْعَلِيُّ",
    frequency: 6,
    timestamp1: 76,
    descAr: "",
    descEn: "",
    pronounciation: "al-a-LEE",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 255 },
      { surah: 22, ayah: 62 },
      { surah: 31, ayah: 30 },
      { surah: 34, ayah: 23 },
      { surah: 40, ayah: 12 },
      { surah: 42, ayah: 4 },
    ],
  },
  50: {
    id: 50,
    rank: 37,
    englishName: "Al-Kabir",
    englishMean: "The Great",
    arabicName: "ٱلْكَبِيرُ",
    frequency: 8,
    timestamp1: 77,
    descAr: "",
    descEn: "",
    pronounciation: "al-ka-BEER",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 255 },
      { surah: 13, ayah: 9 },
      { surah: 22, ayah: 62 },
      { surah: 31, ayah: 30 },
      { surah: 34, ayah: 23 },
      { surah: 35, ayah: 32 },
      { surah: 40, ayah: 12 },
      { surah: 42, ayah: 22 },
      { surah: 85, ayah: 11 },
    ],
  },
  48: {
    id: 48,
    rank: 38,
    englishName: "Al-Hafiz",
    englishMean: "The Preserver",
    arabicName: "ٱلْحَفِيظُ",
    frequency: 0,
    timestamp1: 78,
    descAr: "",
    descEn: "",
    pronounciation: "al-ha-FEEZ",
    quran_hadith: "Hadith",
  },
  30: {
    id: 30,
    rank: 39,
    englishName: "Al-Muqit",
    englishMean: "The Sustainer",
    arabicName: "ٱلْمُقِيتُ",
    frequency: 0,
    timestamp1: 79.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-mu-QEET",
    quran_hadith: "Hadith",
  },
  41: {
    id: 41,
    rank: 40,
    englishName: "Al-Hasib",
    englishMean: "The Reckoner",
    arabicName: "ٱلْحَسِيبُ",
    frequency: 0,
    timestamp1: 80.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-ha-SEEB",
    quran_hadith: "Hadith",
  },
  34: {
    id: 34,
    rank: 41,
    englishName: "Al-Jalil",
    englishMean: "The Majestic",
    arabicName: "ٱلْجَلِيلُ",
    frequency: 0,
    timestamp1: 82,
    descAr: "",
    descEn: "",
    pronounciation: "al-ja-LEEL",
    quran_hadith: "Hadith",
  },
  40: {
    id: 40,
    rank: 42,
    englishName: "Al-Karim",
    englishMean: "The Generous",
    arabicName: "ٱلْكَرِيمُ",
    frequency: 3,
    timestamp1: 83,
    descAr: "",
    descEn: "",
    pronounciation: "al-ka-REEM",
    quran_hadith: "Quran",
    reference: [
      { surah: 23, ayah: 116 },
      { surah: 44, ayah: 49 },
      { surah: 82, ayah: 6 },
    ],
  },
  55: {
    id: 55,
    rank: 43,
    englishName: "Ar-Raqib",
    englishMean: "The Watchful",
    arabicName: "ٱلرَّقِيبُ",
    frequency: 1,
    timestamp1: 84,
    descAr: "",
    descEn: "",
    pronounciation: "ar-ra-QEEB",
    quran_hadith: "Quran",
    reference: [{ surah: 5, ayah: 117 }],
  },
  49: {
    id: 49,
    rank: 44,
    englishName: "Al-Mujib",
    englishMean: "The Responsive",
    arabicName: "ٱلْمُجِيبُ",
    frequency: 0,
    timestamp1: 85.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-mu-JEEB",
    quran_hadith: "Hadith",
  },
  24: {
    id: 24,
    rank: 45,
    englishName: "Al-Wasi'",
    englishMean: "The All-Encompassing",
    arabicName: "ٱلْوَاسِعُ",
    frequency: 0,
    timestamp1: 87,
    descAr: "",
    descEn: "",
    pronounciation: "al-WA-si",
    quran_hadith: "Hadith",
  },
  31: {
    id: 31,
    rank: 46,
    englishName: "Al-Hakim",
    englishMean: "The Wise",
    arabicName: "ٱلْحَكِيمُ",
    frequency: 42,
    timestamp1: 88,
    descAr: "",
    descEn: "",
    pronounciation: "al-ha-KEEM",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 32 },
      { surah: 2, ayah: 129 },
      { surah: 3, ayah: 6 },
      { surah: 3, ayah: 18 },
      { surah: 3, ayah: 58 },
      { surah: 3, ayah: 62 },
      { surah: 3, ayah: 126 },
      { surah: 5, ayah: 118 },
      { surah: 6, ayah: 18 },
      { surah: 6, ayah: 73 },
      { surah: 10, ayah: 1 },
      { surah: 12, ayah: 83 },
      { surah: 12, ayah: 100 },
      { surah: 14, ayah: 4 },
      { surah: 16, ayah: 60 },
      { surah: 27, ayah: 9 },
      { surah: 29, ayah: 26 },
      { surah: 29, ayah: 42 },
      { surah: 30, ayah: 27 },
      { surah: 31, ayah: 2 },
      { surah: 31, ayah: 9 },
      { surah: 34, ayah: 1 },
      { surah: 34, ayah: 27 },
      { surah: 35, ayah: 2 },
      { surah: 36, ayah: 2 },
      { surah: 39, ayah: 1 },
      { surah: 40, ayah: 8 },
      { surah: 42, ayah: 3 },
      { surah: 43, ayah: 84 },
      { surah: 45, ayah: 2 },
      { surah: 45, ayah: 37 },
      { surah: 46, ayah: 2 },
      { surah: 51, ayah: 30 },
      { surah: 57, ayah: 1 },
      { surah: 59, ayah: 1 },
      { surah: 59, ayah: 24 },
      { surah: 60, ayah: 5 },
      { surah: 61, ayah: 1 },
      { surah: 62, ayah: 1 },
      { surah: 62, ayah: 3 },
      { surah: 64, ayah: 18 },
      { surah: 66, ayah: 2 },
    ],
  },
  23: {
    id: 23,
    rank: 47,
    englishName: "Al-Wadud",
    englishMean: "The Loving",
    arabicName: "ٱلْوَدُودُ",
    frequency: 1,
    timestamp1: 89,
    descAr: "",
    descEn: "",
    pronounciation: "al-wa-DOOD",
    quran_hadith: "Quran",
    reference: [{ surah: 85, ayah: 14 }],
  },
  36: {
    id: 36,
    rank: 48,
    englishName: "Al-Majid",
    englishMean: "The Glorious",
    arabicName: "ٱلْمَجِيدُ",
    frequency: 2,
    timestamp1: 90.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-ma-JEED",
    quran_hadith: "Quran",
    reference: [
      { surah: 50, ayah: 1 },
      { surah: 85, ayah: 15 },
    ],
  },
  51: {
    id: 51,
    rank: 49,
    englishName: "Al-Ba'ith",
    englishMean: "The Resurrector",
    arabicName: "ٱلْبَاعِثُ",
    frequency: 0,
    timestamp1: 92,
    descAr: "",
    descEn: "",
    pronounciation: "al-BA-ith",
    quran_hadith: "Hadith",
  },
  52: {
    id: 52,
    rank: 50,
    englishName: "Ash-Shahid",
    englishMean: "The Witness",
    arabicName: "ٱلشَّهِيدُ",
    frequency: 0,
    timestamp1: 93,
    descAr: "",
    descEn: "",
    pronounciation: "ash-sha-HEED",
    quran_hadith: "Hadith",
  },
  53: {
    id: 53,
    rank: 51,
    englishName: "Al-Haqq",
    englishMean: "The Truth",
    arabicName: "ٱلْحَقُّ",
    frequency: 109,
    timestamp1: 94.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-HAQQ",
    quran_hadith: "Quran",
    reference: [
      {
        surah: 2,
        ayah: 26,
      },
      {
        surah: 2,
        ayah: 42,
      },
      {
        surah: 2,
        ayah: 61,
      },
      {
        surah: 2,
        ayah: 91,
      },
      {
        surah: 2,
        ayah: 109,
      },
      {
        surah: 2,
        ayah: 144,
      },
      {
        surah: 2,
        ayah: 146,
      },
      {
        surah: 2,
        ayah: 147,
      },
      {
        surah: 2,
        ayah: 213,
      },
      {
        surah: 2,
        ayah: 282,
      },
      {
        surah: 3,
        ayah: 60,
      },
      {
        surah: 3,
        ayah: 62,
      },
      {
        surah: 3,
        ayah: 71,
      },
      {
        surah: 3,
        ayah: 154,
      },
      {
        surah: 4,
        ayah: 171,
      },
      {
        surah: 5,
        ayah: 48,
      },
      {
        surah: 5,
        ayah: 77,
      },
      {
        surah: 5,
        ayah: 83,
      },
      {
        surah: 5,
        ayah: 84,
      },
      {
        surah: 6,
        ayah: 57,
      },
      {
        surah: 6,
        ayah: 62,
      },
      {
        surah: 6,
        ayah: 66,
      },
      {
        surah: 6,
        ayah: 73,
      },
      {
        surah: 6,
        ayah: 93,
      },
      {
        surah: 7,
        ayah: 8,
      },
      {
        surah: 7,
        ayah: 33,
      },
      {
        surah: 7,
        ayah: 105,
      },
      {
        surah: 7,
        ayah: 118,
      },
      {
        surah: 7,
        ayah: 146,
      },
      {
        surah: 7,
        ayah: 169,
      },
      {
        surah: 8,
        ayah: 6,
      },
      {
        surah: 8,
        ayah: 7,
      },
      {
        surah: 8,
        ayah: 8,
      },
      {
        surah: 8,
        ayah: 32,
      },
      {
        surah: 9,
        ayah: 29,
      },
      {
        surah: 9,
        ayah: 33,
      },
      {
        surah: 9,
        ayah: 48,
      },
      {
        surah: 10,
        ayah: 23,
      },
      {
        surah: 10,
        ayah: 30,
      },
      {
        surah: 10,
        ayah: 32,
      },
      {
        surah: 10,
        ayah: 35,
      },
      {
        surah: 10,
        ayah: 36,
      },
      {
        surah: 10,
        ayah: 76,
      },
      {
        surah: 10,
        ayah: 82,
      },
      {
        surah: 10,
        ayah: 94,
      },
      {
        surah: 10,
        ayah: 108,
      },
      {
        surah: 11,
        ayah: 17,
      },
      {
        surah: 11,
        ayah: 45,
      },
      {
        surah: 11,
        ayah: 120,
      },
      {
        surah: 12,
        ayah: 51,
      },
      {
        surah: 13,
        ayah: 1,
      },
      {
        surah: 13,
        ayah: 14,
      },
      {
        surah: 13,
        ayah: 17,
      },
      {
        surah: 13,
        ayah: 19,
      },
      {
        surah: 14,
        ayah: 22,
      },
      {
        surah: 17,
        ayah: 81,
      },
      {
        surah: 18,
        ayah: 29,
      },
      {
        surah: 18,
        ayah: 44,
      },
      {
        surah: 18,
        ayah: 56,
      },
      {
        surah: 19,
        ayah: 34,
      },
      {
        surah: 20,
        ayah: 114,
      },
      {
        surah: 21,
        ayah: 24,
      },
      {
        surah: 21,
        ayah: 97,
      },
      {
        surah: 22,
        ayah: 6,
      },
      {
        surah: 22,
        ayah: 54,
      },
      {
        surah: 22,
        ayah: 62,
      },
      {
        surah: 23,
        ayah: 71,
      },
      {
        surah: 23,
        ayah: 116,
      },
      {
        surah: 24,
        ayah: 25,
      },
      {
        surah: 24,
        ayah: 49,
      },
      {
        surah: 25,
        ayah: 26,
      },
      {
        surah: 27,
        ayah: 79,
      },
      {
        surah: 28,
        ayah: 39,
      },
      {
        surah: 28,
        ayah: 48,
      },
      {
        surah: 28,
        ayah: 53,
      },
      {
        surah: 28,
        ayah: 75,
      },
      {
        surah: 31,
        ayah: 30,
      },
      {
        surah: 32,
        ayah: 3,
      },
      {
        surah: 33,
        ayah: 4,
      },
      {
        surah: 33,
        ayah: 53,
      },
      {
        surah: 34,
        ayah: 6,
      },
      {
        surah: 34,
        ayah: 23,
      },
      {
        surah: 34,
        ayah: 49,
      },
      {
        surah: 35,
        ayah: 31,
      },
      {
        surah: 40,
        ayah: 5,
      },
      {
        surah: 40,
        ayah: 75,
      },
      {
        surah: 41,
        ayah: 15,
      },
      {
        surah: 41,
        ayah: 53,
      },
      {
        surah: 42,
        ayah: 18,
      },
      {
        surah: 42,
        ayah: 24,
      },
      {
        surah: 42,
        ayah: 42,
      },
      {
        surah: 43,
        ayah: 29,
      },
      {
        surah: 43,
        ayah: 30,
      },
      {
        surah: 46,
        ayah: 20,
      },
      {
        surah: 46,
        ayah: 30,
      },
      {
        surah: 47,
        ayah: 2,
      },
      {
        surah: 47,
        ayah: 3,
      },
      {
        surah: 48,
        ayah: 28,
      },
      {
        surah: 53,
        ayah: 28,
      },
      {
        surah: 57,
        ayah: 16,
      },
      {
        surah: 60,
        ayah: 1,
      },
      {
        surah: 61,
        ayah: 9,
      },
      {
        surah: 78,
        ayah: 39,
      },
    ],
  },
  33: {
    id: 33,
    rank: 52,
    englishName: "Al-Wakil",
    englishMean: "The Trustee",
    arabicName: "ٱلْوَكِيلُ",
    frequency: 1,
    timestamp1: 95.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-wa-KEEL",
    quran_hadith: "Quran",
    reference: [{ surah: 3, ayah: 173 }],
  },
  37: {
    id: 37,
    rank: 53,
    englishName: "Al-Qawiyy",
    englishMean: "The Strong",
    arabicName: "ٱلْقَوِيُّ",
    frequency: 3,
    timestamp1: 96.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-qa-WEE",
    quran_hadith: "Quran",
    reference: [
      { surah: 11, ayah: 66 },
      { surah: 28, ayah: 26 },
      { surah: 42, ayah: 19 },
    ],
  },
  39: {
    id: 39,
    rank: 54,
    englishName: "Al-Matin",
    englishMean: "The Firm",
    arabicName: "ٱلْمَتِينُ",
    frequency: 1,
    timestamp1: 98,
    descAr: "",
    descEn: "",
    pronounciation: "al-ma-TEEN",
    quran_hadith: "Quran",
    reference: [{ surah: 51, ayah: 58 }],
  },
  20: {
    id: 20,
    rank: 55,
    englishName: "Al-Waliyy",
    englishMean: "The Protecting Friend",
    arabicName: "ٱلْوَلِيُّ",
    frequency: 2,
    timestamp1: 99,
    descAr: "",
    descEn: "",
    pronounciation: "al-wa-LEE",
    quran_hadith: "Quran",
    reference: [
      { surah: 42, ayah: 9 },
      { surah: 42, ayah: 28 },
    ],
  },
  54: {
    id: 54,
    rank: 56,
    englishName: "Al-Hamid",
    englishMean: "The Praiseworthy",
    arabicName: "ٱلْحَمِيدُ",
    frequency: 10,
    timestamp1: 100,
    descAr: "",
    descEn: "",
    pronounciation: "al-ha-MEED",
    quran_hadith: "Quran",
    reference: [
      { surah: 14, ayah: 1 },
      { surah: 22, ayah: 24 },
      { surah: 22, ayah: 64 },
      { surah: 31, ayah: 26 },
      { surah: 34, ayah: 6 },
      { surah: 35, ayah: 15 },
      { surah: 42, ayah: 28 },
      { surah: 57, ayah: 24 },
      { surah: 60, ayah: 6 },
      { surah: 85, ayah: 8 },
    ],
  },
  21: {
    id: 21,
    rank: 57,
    englishName: "Al-Muhsi",
    englishMean: "The Accounter",
    arabicName: "ٱلْمُحْصِي",
    frequency: 0,
    timestamp1: 101.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-muh-SEE",
    quran_hadith: "Hadith",
  },
  32: {
    id: 32,
    rank: 58,
    englishName: "Al-Mubdi'",
    englishMean: "The Originator",
    arabicName: "ٱلْمُبْدِئُ",
    frequency: 0,
    timestamp1: 103,
    descAr: "",
    descEn: "",
    pronounciation: "al-mub-DEE",
    quran_hadith: "Hadith",
  },
  38: {
    id: 38,
    rank: 59,
    englishName: "Al-Mu'id",
    englishMean: "The Restorer",
    arabicName: "ٱلْمُعِيدُ",
    frequency: 0,
    timestamp1: 104,
    descAr: "",
    descEn: "",
    pronounciation: "al-mu-EED",
    quran_hadith: "Hadith",
  },
  22: {
    id: 22,
    rank: 60,
    englishName: "Al-Muhyi",
    englishMean: "The Giver of Life",
    arabicName: "ٱلْمُحْيِي",
    frequency: 0,
    timestamp1: 105,
    descAr: "",
    descEn: "",
    pronounciation: "al-muh-YEE",
    quran_hadith: "Hadith",
  },
  102: {
    id: 102,
    rank: 61,
    englishName: "Al-Mumit",
    englishMean: "The Bringer of Death",
    arabicName: "ٱلْمُمِيتُ",
    frequency: 0,
    timestamp1: 106,
    descAr: "",
    descEn: "",
    pronounciation: "al-mu-MEET",
    quran_hadith: "Hadith",
  },
  68: {
    id: 68,
    rank: 62,
    englishName: "Al-Hayy",
    englishMean: "The Ever-Living",
    arabicName: "ٱلْحَيُّ",
    frequency: 12,
    timestamp1: 108,
    descAr: "",
    descEn: "",
    pronounciation: "al-HAYY",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 255 },
      { surah: 3, ayah: 2 },
      { surah: 3, ayah: 27 },
      { surah: 6, ayah: 95 },
      { surah: 10, ayah: 31 },
      { surah: 25, ayah: 58 },
      { surah: 30, ayah: 19 },
      { surah: 40, ayah: 65 },
    ],
  },
  89: {
    id: 89,
    rank: 63,
    englishName: "Al-Qayyum",
    englishMean: "The Self-Sustaining",
    arabicName: "ٱلْقَيُّومُ",
    frequency: 3,
    timestamp1: 109,
    descAr: "",
    descEn: "",
    pronounciation: "al-qay-YOOM",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 255 },
      { surah: 3, ayah: 2 },
      { surah: 20, ayah: 111 },
    ],
  },
  90: {
    id: 90,
    rank: 64,
    englishName: "Al-Wajid",
    englishMean: "The Finder",
    arabicName: "ٱلْوَاجِدُ",
    frequency: 0,
    timestamp1: 110,
    descAr: "",
    descEn: "",
    pronounciation: "al-WA-jid",
    quran_hadith: "Hadith",
  },
  100: {
    id: 100,
    rank: 65,
    englishName: "Al-Majid",
    englishMean: "The Noble",
    arabicName: "ٱلْمَاجِدُ",
    frequency: 0,
    timestamp1: 112.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-MA-jid",
    quran_hadith: "Hadith",
  },
  70: {
    id: 70,
    rank: 66,
    englishName: "Al-Wahid",
    englishMean: "The One",
    arabicName: "ٱلْوَاحِدُ",
    frequency: 6,
    timestamp1: 115,
    descAr: "",
    descEn: "",
    pronounciation: "al-WA-hid",
    quran_hadith: "Quran",
    reference: [
      { surah: 12, ayah: 39 },
      { surah: 13, ayah: 16 },
      { surah: 14, ayah: 48 },
      { surah: 38, ayah: 65 },
      { surah: 39, ayah: 4 },
      { surah: 40, ayah: 16 },
    ],
  },
  71: {
    id: 71,
    rank: 68,
    englishName: "As-Samad",
    englishMean: "The Eternal Refuge",
    arabicName: "ٱلصَّمَدُ",
    frequency: 1,
    timestamp1: 116.5,
    descAr: "",
    descEn: "",
    pronounciation: "as-sa-MAD",
    quran_hadith: "Quran",
    reference: [{ surah: 112, ayah: 2 }],
  },
  88: {
    id: 88,
    rank: 69,
    englishName: "Al-Qadir",
    englishMean: "The Capable",
    arabicName: "ٱلْقَادِرُ",
    frequency: 1,
    timestamp1: 117.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-QA-dir",
    quran_hadith: "Quran",
    reference: [{ surah: 6, ayah: 65 }],
  },
  101: {
    id: 101,
    rank: 70,
    englishName: "Al-Muqtadir",
    englishMean: "The Powerful",
    arabicName: "ٱلْمُقْتَدِرُ",
    frequency: 0,
    timestamp1: 118.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-muq-ta-DIR",
    quran_hadith: "Hadith",
  },
  99: {
    id: 99,
    rank: 71,
    englishName: "Al-Muqaddim",
    englishMean: "The Expediter",
    arabicName: "ٱلْمُقَدِّمُ",
    frequency: 0,
    timestamp1: 120,
    descAr: "",
    descEn: "",
    pronounciation: "al-mu-QAD-dim",
    quran_hadith: "Hadith",
  },
  104: {
    id: 104,
    rank: 72,
    englishName: "Al-Mu'akhkhir",
    englishMean: "The Delayer",
    arabicName: "ٱلْمُؤَخِّرُ",
    frequency: 0,
    timestamp1: 121,
    descAr: "",
    descEn: "",
    pronounciation: "al-mu-AKH-khir",
    quran_hadith: "Hadith",
  },
  69: {
    id: 69,
    rank: 73,
    englishName: "Al-Awwal",
    englishMean: "The First",
    arabicName: "ٱلْأَوَّلُ",
    frequency: 2,
    timestamp1: 122,
    descAr: "",
    descEn: "",
    pronounciation: "al-AW-wal",
    quran_hadith: "Quran",
    reference: [
      { surah: 50, ayah: 15 },
      { surah: 57, ayah: 3 },
    ],
  },
  105: {
    id: 105,
    rank: 74,
    englishName: "Al-Akhir",
    englishMean: "The Last",
    arabicName: "ٱلْآخِرُ",
    frequency: 1,
    timestamp1: 123,
    descAr: "",
    descEn: "",
    pronounciation: "al-A-khir",
    quran_hadith: "Quran",
    reference: [{ surah: 57, ayah: 3 }],
  },
  75: {
    id: 75,
    rank: 75,
    englishName: "Az-Zahir",
    englishMean: "The Manifest",
    arabicName: "ٱلْظَّاهِرُ",
    frequency: 1,
    timestamp1: 125,
    descAr: "",
    descEn: "",
    pronounciation: "az-ZA-hir",
    quran_hadith: "Quran",
    reference: [{ surah: 57, ayah: 3 }],
  },
  77: {
    id: 77,
    rank: 76,
    englishName: "Al-Batin",
    englishMean: "The Hidden",
    arabicName: "ٱلْبَاطِنُ",
    frequency: 1,
    timestamp1: 126,
    descAr: "",
    descEn: "",
    pronounciation: "al-BA-tin",
    quran_hadith: "Quran",
    reference: [{ surah: 57, ayah: 3 }],
  },
  73: {
    id: 73,
    rank: 77,
    englishName: "Al-Wali",
    englishMean: "The Governor",
    arabicName: "ٱلْوَالِي",
    frequency: 0,
    timestamp1: 127,
    descAr: "",
    descEn: "",
    pronounciation: "al-WA-li",
    quran_hadith: "Hadith",
  },
  91: {
    id: 91,
    rank: 78,
    englishName: "Al-Muta'ali",
    englishMean: "The Exalted",
    arabicName: "ٱلْمُتَعَالِي",
    frequency: 1,
    timestamp1: 130,
    descAr: "",
    descEn: "",
    pronounciation: "al-mu-ta-AA-li",
    quran_hadith: "Quran",
    reference: [{ surah: 13, ayah: 9 }],
  },
  92: {
    id: 92,
    rank: 79,
    englishName: "Al-Barr",
    englishMean: "The Source of Goodness",
    arabicName: "ٱلْبَرُّ",
    frequency: 19,
    timestamp1: 132.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-BARR",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 177 },
      { surah: 2, ayah: 189 },
      { surah: 3, ayah: 92 },
      { surah: 5, ayah: 2 },
      { surah: 5, ayah: 96 },
      { surah: 6, ayah: 59 },
      { surah: 6, ayah: 63 },
      { surah: 6, ayah: 97 },
      { surah: 10, ayah: 22 },
      { surah: 17, ayah: 67 },
      { surah: 17, ayah: 68 },
      { surah: 17, ayah: 70 },
      { surah: 27, ayah: 63 },
      { surah: 29, ayah: 65 },
      { surah: 30, ayah: 41 },
      { surah: 31, ayah: 32 },
      { surah: 52, ayah: 28 },
    ],
  },
  93: {
    id: 93,
    rank: 80,
    englishName: "At-Tawwab",
    englishMean: "The Acceptor of Repentance",
    arabicName: "ٱلتَّوَّابُ",
    frequency: 6,
    timestamp1: 133,
    descAr: "",
    descEn: "",
    pronounciation: "at-taw-WAB",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 54 },
      { surah: 2, ayah: 128 },
      { surah: 2, ayah: 160 },
      { surah: 9, ayah: 104 },
      { surah: 9, ayah: 118 },
    ],
  },
  86: {
    id: 86,
    rank: 81,
    englishName: "Al-Muntaqim",
    englishMean: "The Avenger",
    arabicName: "ٱلْمُنْتَقِمُ",
    frequency: 0,
    timestamp1: 134.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-mun-ta-QIM",
    quran_hadith: "Hadith",
  },
  76: {
    id: 76,
    rank: 82,
    englishName: "Al-'Afuww",
    englishMean: "The Pardoner",
    arabicName: "ٱلْعَفُوُّ",
    frequency: 2,
    timestamp1: 135.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-a-FOO",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 219 },
      { surah: 7, ayah: 199 },
    ],
  },
  103: {
    id: 103,
    rank: 83,
    englishName: "Ar-Ra'uf",
    englishMean: "The Most Kind",
    arabicName: "ٱلرَّؤُوفُ",
    frequency: 0,
    timestamp1: 136.5,
    descAr: "",
    descEn: "",
    pronounciation: "ar-ra-OOF",
    quran_hadith: "Hadith",
  },
  72: {
    id: 72,
    rank: 84,
    englishName: "Malik-ul-Mulk",
    englishMean: "Owner of the Kingdom",
    arabicName: "مَالِكُ ٱلْمُلْكِ",
    frequency: 1,
    timestamp1: 139,
    descAr: "",
    descEn: "",
    pronounciation: "MA-lik-ul-MULK",
    quran_hadith: "Quran",
    reference: [{ surah: 3, ayah: 26 }],
  },
  106: {
    id: 106,
    rank: 85,
    englishName: "Dhul-Jalali wal-Ikram",
    englishMean: "Lord of Majesty and Generosity",
    arabicName: "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ",
    frequency: 2,
    timestamp1: 141.5,
    descAr: "",
    descEn: "",
    pronounciation: "dhul-ja-LA-li wal-ik-RAM",
    quran_hadith: "Quran",
    reference: [
      { surah: 55, ayah: 27 },
      { surah: 55, ayah: 78 },
    ],
  },
  85: {
    id: 85,
    rank: 86,
    englishName: "Al-Muqsit",
    englishMean: "The Equitable",
    arabicName: "ٱلْمُقْسِطُ",
    frequency: 0,
    timestamp1: 145.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-muq-SIT",
    quran_hadith: "Hadith",
  },
  81: {
    id: 81,
    rank: 87,
    englishName: "Al-Jami'",
    englishMean: "The Gatherer",
    arabicName: "ٱلْجَامِعُ",
    frequency: 0,
    timestamp1: 147,
    descAr: "",
    descEn: "",
    pronounciation: "al-JA-mi",
    quran_hadith: "Hadith",
  },
  84: {
    id: 84,
    rank: 88,
    englishName: "Al-Ghaniyy",
    englishMean: "The Self-Sufficient",
    arabicName: "ٱلْغَنِيُّ",
    frequency: 8,
    timestamp1: 148,
    descAr: "",
    descEn: "",
    pronounciation: "al-gha-NEE",
    quran_hadith: "Quran",
    reference: [
      { surah: 6, ayah: 133 },
      { surah: 10, ayah: 68 },
      { surah: 22, ayah: 64 },
      { surah: 31, ayah: 26 },
      { surah: 35, ayah: 15 },
      { surah: 47, ayah: 38 },
      { surah: 57, ayah: 24 },
      { surah: 60, ayah: 6 },
    ],
  },
  95: {
    id: 95,
    rank: 89,
    englishName: "Al-Mughni",
    englishMean: "The Enricher",
    arabicName: "ٱلْمُغْنِي",
    frequency: 0,
    timestamp1: 149,
    descAr: "",
    descEn: "",
    pronounciation: "al-mugh-NEE",
    quran_hadith: "Hadith",
  },
  94: {
    id: 94,
    rank: 90,
    englishName: "Al-Mani'",
    englishMean: "The Preventer",
    arabicName: "ٱلْمَانِعُ",
    frequency: 0,
    timestamp1: 151,
    descAr: "",
    descEn: "",
    pronounciation: "al-MA-ni",
    quran_hadith: "Hadith",
  },
  87: {
    id: 87,
    rank: 91,
    englishName: "Ad-Darr",
    englishMean: "The Distresser",
    arabicName: "ٱلضَّارَّ",
    frequency: 0,
    timestamp1: 152.5,
    descAr: "",
    descEn: "",
    pronounciation: "ad-DARR",
    quran_hadith: "Hadith",
  },
  80: {
    id: 80,
    rank: 92,
    englishName: "An-Nafi'",
    englishMean: "The Benefactor",
    arabicName: "ٱلنَّافِعُ",
    frequency: 0,
    timestamp1: 153.5,
    descAr: "",
    descEn: "",
    pronounciation: "an-NA-fi",
    quran_hadith: "Hadith",
  },
  78: {
    id: 78,
    rank: 93,
    englishName: "An-Nur",
    englishMean: "The Light",
    arabicName: "ٱلنُّورُ",
    frequency: 10,
    timestamp1: 154.5,
    descAr: "",
    descEn: "",
    pronounciation: "an-NOOR",
    quran_hadith: "Quran",
    reference: [
      { surah: 2, ayah: 257 },
      { surah: 5, ayah: 16 },
      { surah: 7, ayah: 157 },
      { surah: 14, ayah: 1 },
      { surah: 14, ayah: 5 },
      { surah: 33, ayah: 43 },
      { surah: 35, ayah: 20 },
      { surah: 57, ayah: 9 },
      { surah: 65, ayah: 11 },
    ],
  },
  74: {
    id: 74,
    rank: 94,
    englishName: "Al-Hadi",
    englishMean: "The Guide",
    arabicName: "ٱلْهَادِي",
    frequency: 0,
    timestamp1: 155.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-HA-di",
    quran_hadith: "Hadith",
  },
  97: {
    id: 97,
    rank: 95,
    englishName: "Al-Badi'",
    englishMean: "The Incomparable",
    arabicName: "ٱلْبَدِيعُ",
    frequency: 0,
    timestamp1: 157,
    descAr: "",
    descEn: "",
    pronounciation: "al-ba-DEE",
    quran_hadith: "Hadith",
  },
  96: {
    id: 96,
    rank: 96,
    englishName: "Al-Baqi",
    englishMean: "The Everlasting",
    arabicName: "ٱلْبَاقِي",
    frequency: 0,
    timestamp1: 158.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-BA-qi",
    quran_hadith: "Hadith",
  },
  79: {
    id: 79,
    rank: 97,
    englishName: "Al-Warith",
    englishMean: "The Inheritor",
    arabicName: "ٱلْوَارِثُ",
    frequency: 1,
    timestamp1: 159.5,
    descAr: "",
    descEn: "",
    pronounciation: "al-WA-rith",
    quran_hadith: "Quran",
    reference: [{ surah: 2, ayah: 233 }],
  },
  82: {
    id: 82,
    rank: 98,
    englishName: "Ar-Rashid",
    englishMean: "The Righteous Teacher",
    arabicName: "ٱلْرَّشِيدُ",
    frequency: 1,
    timestamp1: 160.5,
    descAr: "",
    descEn: "",
    pronounciation: "ar-ra-SHEED",
    quran_hadith: "Quran",
    reference: [{ surah: 11, ayah: 87 }],
  },
  83: {
    id: 83,
    rank: 99,
    englishName: "As-Sabur",
    englishMean: "The Patient",
    arabicName: "ٱلصَّبُورُ",
    frequency: 0,
    timestamp1: 161.5,
    descAr: "",
    descEn: "",
    pronounciation: "as-sa-BOOR",
    quran_hadith: "Hadith",
  },
};
