// Dictionary mapping name IDs to their details
export default {
  13: {
    id: 13,
    rank: 1,
    englishName: "Ar-Rahman",
    arabicName: "ٱلرَّحْمَٰنُ",
    frequency: 57,
  },
  12: {
    id: 12,
    rank: 2,
    englishName: "Ar-Raheem",
    arabicName: "ٱلرَّحِيمُ",
    frequency: 123,
  },
  8: {
    id: 8,
    rank: 3,
    englishName: "Al-Malik",
    arabicName: "ٱلْمَلِكُ",
    frequency: null,
  },
  11: {
    id: 11,
    rank: 4,
    englishName: "Al-Quddus",
    arabicName: "ٱلْقُدُّوسُ",
    frequency: 2,
  },
  10: {
    id: 10,
    rank: 5,
    englishName: "As-Salam",
    arabicName: "ٱلسَّلَامُ",
    frequency: 1,
  },
  9: {
    id: 9,
    rank: 6,
    englishName: "Al-Mu'min",
    arabicName: "ٱلْمُؤْمِنُ",
    frequency: 1,
  },
  18: {
    id: 18,
    rank: 7,
    englishName: "Al-Muhaymin",
    arabicName: "ٱلْمُهَيْمِنُ",
    frequency: null,
  },
  19: {
    id: 19,
    rank: 8,
    englishName: "Al-'Aziz",
    arabicName: "ٱلْعَزِيزُ",
    frequency: null,
  },
  14: {
    id: 14,
    rank: 9,
    englishName: "Al-Jabbar",
    arabicName: "ٱلْجَبَّارُ",
    frequency: null,
  },
  15: {
    id: 15,
    rank: 10,
    englishName: "Al-Mutakabbir",
    arabicName: "ٱلْمُتَكَبِّرُ",
    frequency: null,
  },
  16: {
    id: 16,
    rank: 11,
    englishName: "Al-Khaliq",
    arabicName: "ٱلْخَالِقُ",
    frequency: null,
  },
  17: {
    id: 17,
    rank: 12,
    englishName: "Al-Bari'",
    arabicName: "ٱلْبَارِئُ",
    frequency: null,
  },
  27: {
    id: 27,
    rank: 13,
    englishName: "Al-Musawwir",
    arabicName: "ٱلْمُصَوِّرُ",
    frequency: null,
  },
  64: {
    id: 64,
    rank: 14,
    englishName: "Al-Ghaffar",
    arabicName: "ٱلْغَفَّارُ",
    frequency: null,
  },
  65: {
    id: 65,
    rank: 15,
    englishName: "Al-Qahhar",
    arabicName: "ٱلْقَهَّارُ",
    frequency: null,
  },
  58: {
    id: 58,
    rank: 16,
    englishName: "Al-Wahhab",
    arabicName: "ٱلْوَهَّابُ",
    frequency: null,
  },
  66: {
    id: 66,
    rank: 17,
    englishName: "Ar-Razzaq",
    arabicName: "ٱلرَّزَّاقُ",
    frequency: null,
  },
  67: {
    id: 67,
    rank: 18,
    englishName: "Al-Fattah",
    arabicName: "ٱلْفَتَّاحُ",
    frequency: null,
  },
  63: {
    id: 63,
    rank: 19,
    englishName: "Al-'Alim",
    arabicName: "ٱلْعَلِيمُ",
    frequency: null,
  },
  28: {
    id: 28,
    rank: 20,
    englishName: "Al-Qabid",
    arabicName: "ٱلْقَابِضُ",
    frequency: null,
  },
  29: {
    id: 29,
    rank: 21,
    englishName: "Al-Basit",
    arabicName: "ٱلْبَاسِطُ",
    frequency: null,
  },
  57: {
    id: 57,
    rank: 22,
    englishName: "Al-Khafid",
    arabicName: "ٱلْخَافِضُ",
    frequency: null,
  },
  59: {
    id: 59,
    rank: 23,
    englishName: "Ar-Rafi'",
    arabicName: "ٱلرَّافِعُ",
    frequency: null,
  },
  60: {
    id: 60,
    rank: 24,
    englishName: "Al-Mu'izz",
    arabicName: "ٱلْمُعِزُّ",
    frequency: null,
  },
  46: {
    id: 46,
    rank: 25,
    englishName: "Al-Mudhill",
    arabicName: "ٱلْمُذِلُّ",
    frequency: null,
  },
  45: {
    id: 45,
    rank: 26,
    englishName: "As-Sami'",
    arabicName: "ٱلسَّمِيعُ",
    frequency: null,
  },
  43: {
    id: 43,
    rank: 27,
    englishName: "Al-Basir",
    arabicName: "ٱلْبَصِيرُ",
    frequency: null,
  },
  25: {
    id: 25,
    rank: 28,
    englishName: "Al-Hakam",
    arabicName: "ٱلْحَكَمُ",
    frequency: null,
  },
  26: {
    id: 26,
    rank: 29,
    englishName: "Al-'Adl",
    arabicName: "ٱلْعَدْلُ",
    frequency: null,
  },
  61: {
    id: 61,
    rank: 30,
    englishName: "Al-Latif",
    arabicName: "ٱللَّطِيفُ",
    frequency: null,
  },
  47: {
    id: 47,
    rank: 31,
    englishName: "Al-Khabir",
    arabicName: "ٱلْخَبِيرُ",
    frequency: null,
  },
  56: {
    id: 56,
    rank: 32,
    englishName: "Al-Halim",
    arabicName: "ٱلْحَلِيمُ",
    frequency: null,
  },
  44: {
    id: 44,
    rank: 33,
    englishName: "Al-'Azim",
    arabicName: "ٱلْعَظِيمُ",
    frequency: null,
  },
  42: {
    id: 42,
    rank: 34,
    englishName: "Al-Ghafur",
    arabicName: "ٱلْغَفُورُ",
    frequency: null,
  },
  62: {
    id: 62,
    rank: 35,
    englishName: "Ash-Shakur",
    arabicName: "ٱلشَّكُورُ",
    frequency: null,
  },
  35: {
    id: 35,
    rank: 36,
    englishName: "Al-'Aliyy",
    arabicName: "ٱلْعَلِيُّ",
    frequency: null,
  },
  50: {
    id: 50,
    rank: 37,
    englishName: "Al-Kabir",
    arabicName: "ٱلْكَبِيرُ",
    frequency: null,
  },
  48: {
    id: 48,
    rank: 38,
    englishName: "Al-Hafiz",
    arabicName: "ٱلْحَفِيظُ",
    frequency: null,
  },
  30: {
    id: 30,
    rank: 39,
    englishName: "Al-Muqit",
    arabicName: "ٱلْمُقِيتُ",
    frequency: null,
  },
  41: {
    id: 41,
    rank: 40,
    englishName: "Al-Hasib",
    arabicName: "ٱلْحَسِيبُ",
    frequency: null,
  },
  34: {
    id: 34,
    rank: 41,
    englishName: "Al-Jalil",
    arabicName: "ٱلْجَلِيلُ",
    frequency: null,
  },
  40: {
    id: 40,
    rank: 42,
    englishName: "Al-Karim",
    arabicName: "ٱلْكَرِيمُ",
    frequency: null,
  },
  55: {
    id: 55,
    rank: 43,
    englishName: "Ar-Raqib",
    arabicName: "ٱلرَّقِيبُ",
    frequency: null,
  },
  49: {
    id: 49,
    rank: 44,
    englishName: "Al-Mujib",
    arabicName: "ٱلْمُجِيبُ",
    frequency: null,
  },
  24: {
    id: 24,
    rank: 45,
    englishName: "Al-Wasi'",
    arabicName: "ٱلْوَاسِعُ",
    frequency: null,
  },
  31: {
    id: 31,
    rank: 46,
    englishName: "Al-Hakim",
    arabicName: "ٱلْحَكِيمُ",
    frequency: null,
  },
  23: {
    id: 23,
    rank: 47,
    englishName: "Al-Wadud",
    arabicName: "ٱلْوَدُودُ",
    frequency: null,
  },
  36: {
    id: 36,
    rank: 48,
    englishName: "Al-Majid",
    arabicName: "ٱلْمَجِيدُ",
    frequency: null,
  },
  51: {
    id: 51,
    rank: 49,
    englishName: "Al-Ba'ith",
    arabicName: "ٱلْبَاعِثُ",
    frequency: null,
  },
  52: {
    id: 52,
    rank: 50,
    englishName: "Ash-Shahid",
    arabicName: "ٱلشَّهِيدُ",
    frequency: null,
  },
  53: {
    id: 53,
    rank: 51,
    englishName: "Al-Haqq",
    arabicName: "ٱلْحَقُّ",
    frequency: null,
  },
  33: {
    id: 33,
    rank: 52,
    englishName: "Al-Wakil",
    arabicName: "ٱلْوَكِيلُ",
    frequency: null,
  },
  37: {
    id: 37,
    rank: 53,
    englishName: "Al-Qawiyy",
    arabicName: "ٱلْقَوِيُّ",
    frequency: null,
  },
  39: {
    id: 39,
    rank: 54,
    englishName: "Al-Matin",
    arabicName: "ٱلْمَتِينُ",
    frequency: null,
  },
  20: {
    id: 20,
    rank: 55,
    englishName: "Al-Waliyy",
    arabicName: "ٱلْوَلِيُّ",
    frequency: null,
  },
  54: {
    id: 54,
    rank: 56,
    englishName: "Al-Hamid",
    arabicName: "ٱلْحَمِيدُ",
    frequency: null,
  },
  21: {
    id: 21,
    rank: 57,
    englishName: "Al-Muhsi",
    arabicName: "ٱلْمُحْصِي",
    frequency: null,
  },
  32: {
    id: 32,
    rank: 58,
    englishName: "Al-Mubdi'",
    arabicName: "ٱلْمُبْدِئُ",
    frequency: null,
  },
  38: {
    id: 38,
    rank: 59,
    englishName: "Al-Mu'id",
    arabicName: "ٱلْمُعِيدُ",
    frequency: null,
  },
  22: {
    id: 22,
    rank: 60,
    englishName: "Al-Muhyi",
    arabicName: "ٱلْمُحْيِي",
    frequency: null,
  },
  102: {
    id: 102,
    rank: 61,
    englishName: "Al-Mumit",
    arabicName: "ٱلْمُمِيتُ",
    frequency: null,
  },
  68: {
    id: 68,
    rank: 62,
    englishName: "Al-Hayy",
    arabicName: "ٱلْحَيُّ",
    frequency: 5,
  },
  89: {
    id: 89,
    rank: 63,
    englishName: "Al-Qayyum",
    arabicName: "ٱلْقَيُّومُ",
    frequency: 3,
  },
  90: {
    id: 90,
    rank: 64,
    englishName: "Al-Wajid",
    arabicName: "ٱلْوَاجِدُ",
    frequency: null,
  },
  100: {
    id: 100,
    rank: 65,
    englishName: "Al-Majid",
    arabicName: "ٱلْمَاجِدُ",
    frequency: null,
  },
  70: {
    id: 70,
    rank: 66,
    englishName: "Al-Wahid",
    arabicName: "ٱلْوَاحِدُ",
    frequency: null,
  },
  71: {
    id: 71,
    rank: 68,
    englishName: "As-Samad",
    arabicName: "ٱلصَّمَدُ",
    frequency: null,
  },
  88: {
    id: 88,
    rank: 69,
    englishName: "Al-Qadir",
    arabicName: "ٱلْقَادِرُ",
    frequency: null,
  },
  101: {
    id: 101,
    rank: 70,
    englishName: "Al-Muqtadir",
    arabicName: "ٱلْمُقْتَدِرُ",
    frequency: null,
  },
  99: {
    id: 99,
    rank: 71,
    englishName: "Al-Muqaddim",
    arabicName: "ٱلْمُقَدِّمُ",
    frequency: null,
  },
  104: {
    id: 104,
    rank: 72,
    englishName: "Al-Mu'akhkhir",
    arabicName: "ٱلْمُؤَخِّرُ",
    frequency: null,
  },
  69: {
    id: 69,
    rank: 73,
    englishName: "Al-Awwal",
    arabicName: "ٱلْأَوَّلُ",
    frequency: null,
  },
  105: {
    id: 105,
    rank: 74,
    englishName: "Al-Akhir",
    arabicName: "ٱلْآخِرُ",
    frequency: null,
  },
  75: {
    id: 75,
    rank: 75,
    englishName: "Az-Zahir",
    arabicName: "ٱلْظَّاهِرُ",
    frequency: null,
  },
  77: {
    id: 77,
    rank: 76,
    englishName: "Al-Batin",
    arabicName: "ٱلْبَاطِنُ",
    frequency: null,
  },
  73: {
    id: 73,
    rank: 77,
    englishName: "Al-Wali",
    arabicName: "ٱلْوَالِي",
    frequency: null,
  },
  91: {
    id: 91,
    rank: 78,
    englishName: "Al-Muta'ali",
    arabicName: "ٱلْمُتَعَالِي",
    frequency: null,
  },
  92: {
    id: 92,
    rank: 79,
    englishName: "Al-Barr",
    arabicName: "ٱلْبَرُّ",
    frequency: null,
  },
  93: {
    id: 93,
    rank: 80,
    englishName: "At-Tawwab",
    arabicName: "ٱلتَّوَّابُ",
    frequency: null,
  },
  86: {
    id: 86,
    rank: 81,
    englishName: "Al-Muntaqim",
    arabicName: "ٱلْمُنْتَقِمُ",
    frequency: null,
  },
  76: {
    id: 76,
    rank: 82,
    englishName: "Al-'Afuww",
    arabicName: "ٱلْعَفُوُّ",
    frequency: null,
  },
  103: {
    id: 103,
    rank: 83,
    englishName: "Ar-Ra'uf",
    arabicName: "ٱلرَّؤُوفُ",
    frequency: null,
  },
  72: {
    id: 72,
    rank: 84,
    englishName: "Malik-ul-Mulk",
    arabicName: "مَالِكُ ٱلْمُلْكِ",
    frequency: null,
  },
  106: {
    id: 106,
    rank: 85,
    englishName: "Dhul-Jalali wal-Ikram",
    arabicName: "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ",
    frequency: null,
  },
  85: {
    id: 85,
    rank: 86,
    englishName: "Al-Muqsit",
    arabicName: "ٱلْمُقْسِطُ",
    frequency: null,
  },
  81: {
    id: 81,
    rank: 87,
    englishName: "Al-Jami'",
    arabicName: "ٱلْجَامِعُ",
    frequency: null,
  },
  84: {
    id: 84,
    rank: 88,
    englishName: "Al-Ghaniyy",
    arabicName: "ٱلْغَنِيُّ",
    frequency: null,
  },
  95: {
    id: 95,
    rank: 89,
    englishName: "Al-Mughni",
    arabicName: "ٱلْمُغْنِي",
    frequency: null,
  },
  94: {
    id: 94,
    rank: 90,
    englishName: "Al-Mani'",
    arabicName: "ٱلْمَانِعُ",
    frequency: null,
  },
  87: {
    id: 87,
    rank: 91,
    englishName: "Ad-Darr",
    arabicName: "ٱلضَّارَّ",
    frequency: null,
  },
  80: {
    id: 80,
    rank: 92,
    englishName: "An-Nafi'",
    arabicName: "ٱلنَّافِعُ",
    frequency: null,
  },
  78: {
    id: 78,
    rank: 93,
    englishName: "An-Nur",
    arabicName: "ٱلنُّورُ",
    frequency: null,
  },
  74: {
    id: 74,
    rank: 94,
    englishName: "Al-Hadi",
    arabicName: "ٱلْهَادِي",
    frequency: null,
  },
  97: {
    id: 97,
    rank: 95,
    englishName: "Al-Badi'",
    arabicName: "ٱلْبَدِيعُ",
    frequency: null,
  },
  96: {
    id: 96,
    rank: 96,
    englishName: "Al-Baqi",
    arabicName: "ٱلْبَاقِي",
    frequency: null,
  },
  79: {
    id: 79,
    rank: 97,
    englishName: "Al-Warith",
    arabicName: "ٱلْوَارِثُ",
    frequency: null,
  },
  82: {
    id: 82,
    rank: 98,
    englishName: "Ar-Rashid",
    arabicName: "ٱلْرَّشِيدُ",
    frequency: null,
  },
  83: {
    id: 83,
    rank: 99,
    englishName: "As-Sabur",
    arabicName: "ٱلصَّبُورُ",
    frequency: null,
  },
};
