// Dictionary mapping name IDs to their details with personalities
export default {
  2: {
    id: 2,
    arabicName: "الله",
    englishName: "Allah'",
    personAr: "جلال بن عبد الله",
    personEn: "Jalel Ben Abdallah",
    descAr: "رسام وفنان تونسي",
    descEn: "Tunisian painter and artist",
    linkAr:
      "https://mathaf.org.qa/ar/encyclopedia/artists-biographies/jellal-ben-abdallah/",
    linkEn:
      "https://www.galerielmarsa.com/artists/47-jellal-ben-abdallah/biography/",
    common: "Yes",
  },
  13: {
    id: 13,
    arabicName: "الرحمن",
    englishName: "Ar-Rahman",
    personAr: "عبد الرحمن بن خلدون",
    personEn: "Abderrahman Ibn Khaldun",
    descAr: "مؤرخ عربي وأب علم الاجتماع",
    descEn: "Tunisian historian and father of sociology",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%A7%D8%A8%D9%86_%D8%AE%D9%84%D8%AF%D9%88%D9%86",
    linkEn: "https://en.wikipedia.org/wiki/Ibn_Khaldun",
    common: "Yes",
  },
  12: {
    id: 12,
    arabicName: "الرحيم",
    englishName: "Ar-Raheem",
    personAr: "سعاد عبد الرحيم",
    personEn: "Souad Abderrahim",
    descAr: "رئيسة بلدية تونس",
    descEn: "Mayor of Tunis",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B3%D8%B9%D8%A7%D8%AF_%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%B1%D8%AD%D9%8A%D9%85",
    linkEn: "https://en.wikipedia.org/wiki/Souad_Abderrahim",
    common: "Yes",
  },
  8: {
    id: 8,
    arabicName: "الملك",
    englishName: "Al-Malik",
    personAr: "عبد الملك العريف",
    personEn: "Abdelmalek Arif",
    descAr: "وزير الإعلام التونسي السابق",
    descEn: "Tunisia's Former Minister of Media",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%85%D9%84%D9%83_%D8%A7%D9%84%D8%B9%D8%B1%D9%8A%D9%81",
    linkEn: "https://fr.wikipedia.org/wiki/Abdelmalek_La%C3%A2rif",
    common: "Yes",
  },
  11: {
    id: 11,
    arabicName: "القدوس",
    englishName: "Al-Quddus",
    personAr: "عبد القدوس السعداوي",
    personEn: "Abdelkodous Saadaoui",
    descAr: " كاتب الدولةالسابق لدى وزارة الشباب والرياضة",
    descEn:
      "Former Secretary of State to the Minister of Youth and Sports 2017",
    linkAr:
      "https://www.nessma.tv/ar/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1-%D9%88%D8%B7%D9%86%D9%8A%D8%A9/actu/%D8%A7%D9%84%D8%B3%D9%8A%D8%B1%D8%A9-%D8%A7%D9%84%D8%B0%D8%A7%D8%AA%D9%8A%D8%A9-%D9%84%D9%83%D8%A7%D8%AA%D8%A8-%D8%AF%D9%88%D9%84%D8%A9-%D9%84%D8%AF%D9%89-%D9%88%D8%B2%D9%8A%D8%B1%D8%A9-%D8%A7%D9%84%D8%B4%D8%A8%D8%A7%D8%A8-%D9%88%D8%A7%D9%84%D8%B1%D9%8A%D8%A7%D8%B6%D8%A9-%D9%85%D9%83%D9%84%D9%81-%D8%A8%D8%A7%D9%84%D8%B4%D8%A8%D8%A7%D8%A8-%D8%B9%D8%A8%D8%AF-%D8%A7%D9%84%D9%82%D8%AF%D9%88%D8%B3-%D8%B3%D8%B9%D8%AF%D8%A7%D9%88%D9%8A-4217/49476",
    linkEn:
      "https://www.nessma.tv/ar/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1-%D9%88%D8%B7%D9%86%D9%8A%D8%A9/actu/%D8%A7%D9%84%D8%B3%D9%8A%D8%B1%D8%A9-%D8%A7%D9%84%D8%B0%D8%A7%D8%AA%D9%8A%D8%A9-%D9%84%D9%83%D8%A7%D8%AA%D8%A8-%D8%AF%D9%88%D9%84%D8%A9-%D9%84%D8%AF%D9%89-%D9%88%D8%B2%D9%8A%D8%B1%D8%A9-%D8%A7%D9%84%D8%B4%D8%A8%D8%A7%D8%A8-%D9%88%D8%A7%D9%84%D8%B1%D9%8A%D8%A7%D8%B6%D8%A9-%D9%85%D9%83%D9%84%D9%81-%D8%A8%D8%A7%D9%84%D8%B4%D8%A8%D8%A7%D8%A8-%D8%B9%D8%A8%D8%AF-%D8%A7%D9%84%D9%82%D8%AF%D9%88%D8%B3-%D8%B3%D8%B9%D8%AF%D8%A7%D9%88%D9%8A-4217/49476",
    common: "Yes",
  },
  10: {
    id: 10,
    arabicName: "السلام",
    englishName: "As-Salam",
    personAr: "رفيق عبد السلام",
    personEn: "Rafik Abdessalem",
    descAr: "وزير خارجية تونس السابق",
    descEn: "Former Minister of Foreign Affairs of Tunisia",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B1%D9%81%D9%8A%D9%82_%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%B3%D9%84%D8%A7%D9%85",
    linkEn: "https://en.wikipedia.org/wiki/Rafik_Abdessalem",
    common: "Yes",
  },
  9: {
    id: 9,
    arabicName: "المؤمن",
    englishName: "Al-Mu'min",
    personAr: "عبد المؤمن بن علي",
    personEn: "Abd al-Mu'min",
    descAr: "حاكم دولة الموحديين",
    descEn: "Ruler of the Almohad Caliphate",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%85%D8%A4%D9%85%D9%86_%D8%A8%D9%86_%D8%B9%D9%84%D9%8A",
    linkEn: "https://en.wikipedia.org/wiki/Abd_al-Mu%27min",
    common: "Yes",
  },
  18: {
    id: 18,
    arabicName: "المهيمن",
    englishName: "Al-Muhaymin",
    personAr: "عبد المهيمن أبو السمح",
    personEn: "Abdul-Muhaymin Abu Al-Samh",
    descAr: "امام وخطيب المسجد الحرام",
    descEn: "Imam of the sacred Mosque of Mecca",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%85%D9%87%D9%8A%D9%85%D9%86_%D8%A3%D8%A8%D9%88_%D8%A7%D9%84%D8%B3%D9%85%D8%AD",
    linkEn: "",
    common: "Yes",
  },
  19: {
    id: 19,
    arabicName: "العزيز",
    englishName: "Al-'Aziz",
    personAr: "عبد العزيز الثعالبي",
    personEn: "Abdelaziz Thaalbi",
    descAr: "زعيم استقلال ومصلح تونسي",
    descEn: "Tunisian independence leader and reformer",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%B9%D8%B2%D9%8A%D8%B2_%D8%A7%D9%84%D8%AB%D8%B9%D8%A7%D9%84%D8%A8%D9%8A",
    linkEn: "https://en.wikipedia.org/wiki/Abdelaziz_Thaalbi",
    common: "Yes",
  },
  14: {
    id: 14,
    arabicName: "الجبار",
    englishName: "Al-Jabbar",
    personAr: "عبد الجبار مشوش",
    personEn: "Abdeljabar Machouch",
    descAr: "لاعب كرة قدم سابق في الترجي الرياضي التونسي",
    descEn: "Former Tunisian footballer for Espérance de Tunis",
    linkAr: "",
    linkEn: "https://en.wikipedia.org/wiki/Abdeljabar_Machouche",
    common: "Yes",
  },
  15: {
    id: 15,
    arabicName: "المتكبر",
    englishName: "Al-Mutakabbir",
    personAr: "عبد المتكبر",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  16: {
    id: 16,
    arabicName: "الخالق",
    englishName: "Al-Khaliq",
    personAr: "عبد الخالق السعداوي",
    personEn: "Abdelkhalak Saadaoui",
    descAr: "صحفي ومعلق رياضي تونسي",
    descEn: "Tunisian journalist and sports commentator",
    linkAr: "",
    linkEn: "",
    common: "Yes",
  },
  17: {
    id: 17,
    arabicName: "البارئ",
    englishName: "Al-Bari'",
    personAr: "عبد الباري عطوان",
    personEn: "Abdel Bari Atwan",
    descAr: "صحفي وكاتب فلسطيني بريطاني",
    descEn: "Palestinian-British journalist and author",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%A8%D8%A7%D8%B1%D9%8A_%D8%B9%D8%B7%D9%88%D8%A7%D9%86",
    linkEn: "https://en.wikipedia.org/wiki/Abdel_Bari_Atwan",
    common: "Yes",
  },
  27: {
    id: 27,
    arabicName: "المصور",
    englishName: "Al-Musawwir",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  64: {
    id: 64,
    arabicName: "الغفار",
    englishName: "Al-Ghaffar",
    personAr: "أنيس عبد الغفار",
    personEn: "Anis Abdelghafar",
    descAr: "مغني تونسي",
    descEn: "Tunisian Singer",
    linkAr: "",
    linkEn: "",
    common: "Yes",
  },
  65: {
    id: 65,
    arabicName: "القهار",
    englishName: "Al-Qahhar",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  58: {
    id: 58,
    arabicName: "الوهاب",
    englishName: "Al-Wahhab",
    personAr: "عبد الوهاب بن عياد",
    personEn: "Abdelwahab Ben Ayed",
    descAr: "رجل أعمال تونسي",
    descEn: "Tunisian businessman and entrepreneur",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%88%D9%87%D8%A7%D8%A8_%D8%A8%D9%86_%D8%B9%D9%8A%D8%A7%D8%AF",
    linkEn:
      "https://www.marketscreener.com/insider/ABDELWAHEB-BEN-AYED-A0T4VD/#:~:text=Abdelwaheb%20ben%20Ayed%20is%20the,founder%20of%20Founders%20Capital%20Partners.",
    common: "Yes",
  },
  66: {
    id: 66,
    arabicName: "الرزاق",
    englishName: "Ar-Razzaq",
    personAr: "عبد الرزاق الشّابي",
    personEn: "Abderrazak ElChebbi",
    descAr: "مذيع و إعلامي تونسي",
    descEn: "Tunisian broadcaster and media personality",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%B1%D8%B2%D8%A7%D9%82_%D8%A7%D9%84%D8%B4%D8%A7%D8%A8%D9%8A",
    linkEn: "",
    common: "Yes",
  },
  67: {
    id: 67,
    arabicName: "الفتاح",
    englishName: "Al-Fattah",
    personAr: "عبد الفتاح مورو",
    personEn: "Abdelfattah Mourou",
    descAr: "سياسي ومحامي تونسي سابق",
    descEn: "Tunisian former politician and lawyer",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%81%D8%AA%D8%A7%D8%AD_%D9%85%D9%88%D8%B1%D9%88",
    linkEn: "https://en.wikipedia.org/wiki/Abdelfattah_Mourou",
    common: "Yes",
  },
  63: {
    id: 63,
    arabicName: "العليم",
    englishName: "Al-'Alim",
    personAr: "ممدوح عبد العليم",
    personEn: "Mamdouh Abd El Alim",
    descAr: "ممثل مصري",
    descEn: "Egyptian actor",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D9%85%D9%85%D8%AF%D9%88%D8%AD_%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%B9%D9%84%D9%8A%D9%85",
    linkEn: "https://en.wikipedia.org/wiki/Mamdouh_Abdel-Alim",
    common: "Yes",
  },
  28: {
    id: 28,
    arabicName: "القابض",
    englishName: "Al-Qabid",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  29: {
    id: 29,
    arabicName: "الباسط",
    englishName: "Al-Basit",
    personAr: "عبد الباسط عبد الصمد",
    personEn: "Abdel Basset Abdel Samad",
    descAr: "قارئ قرآن مصري",
    descEn: "Egyptian Quran reciter",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%A8%D8%A7%D8%B3%D8%B7_%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%B5%D9%85%D8%AF",
    linkEn: "https://en.wikipedia.org/wiki/Abdul_Basit_'Abd_us-Samad",
    common: "Yes",
  },
  57: {
    id: 57,
    arabicName: "الخافض",
    englishName: "Al-Khafid",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  59: {
    id: 59,
    arabicName: "الرافع",
    englishName: "Ar-Rafi'",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  60: {
    id: 60,
    arabicName: "المعز",
    englishName: "Al-Mu'izz",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  46: {
    id: 46,
    arabicName: "المذل",
    englishName: "Al-Mudhill",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  45: {
    id: 45,
    arabicName: "السميع",
    englishName: "As-Sami'",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  43: {
    id: 43,
    arabicName: "البصير",
    englishName: "Al-Basir",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  25: {
    id: 25,
    arabicName: "الحكم",
    englishName: "Al-Hakam",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  26: {
    id: 26,
    arabicName: "العدل",
    englishName: "Al-'Adl",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  61: {
    id: 61,
    arabicName: "اللطيف",
    englishName: "Al-Latif",
    personAr: "عبد اللطيف المكي",
    personEn: "Abdellatif Mekki",
    descAr: "سياسي تونسي ووزير صحة سابق",
    descEn: "Tunisian politician and former Minister of Health",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%84%D8%B7%D9%8A%D9%81_%D8%A7%D9%84%D9%85%D9%83%D9%8A",
    linkEn: "https://en.wikipedia.org/wiki/Abdellatif_Mekki",
    common: "Yes",
  },
  47: {
    id: 47,
    arabicName: "الخبير",
    englishName: "Al-Khabir",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  56: {
    id: 56,
    arabicName: "الحليم",
    englishName: "Al-Halim",
    personAr: "عبد الحليم حافظ",
    personEn: "Abdel Halim Hafez",
    descAr: "مغني وممثل مصري",
    descEn: "Egyptian singer and actor",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%AD%D9%84%D9%8A%D9%85_%D8%AD%D8%A7%D9%81%D8%B8",
    linkEn: "https://en.wikipedia.org/wiki/Abdel_Halim_Hafez",
    common: "Yes",
  },
  44: {
    id: 44,
    arabicName: "العظيم",
    englishName: "Al-'Azim",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  42: {
    id: 42,
    arabicName: "الغفور",
    englishName: "Al-Ghafur",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  62: {
    id: 62,
    arabicName: "الشكور",
    englishName: "Ash-Shakur",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  35: {
    id: 35,
    arabicName: "العلي",
    englishName: "Al-'Aliyy",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  50: {
    id: 50,
    arabicName: "الكبير",
    englishName: "Al-Kabir",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  48: {
    id: 48,
    arabicName: "الحفيظ",
    englishName: "Al-Hafiz",
    personAr: "سمير عبد الحفيظ",
    personEn: "Samir Abdelhafid",
    descAr: "وزير الاقتصاد والتخطيط التونسي",
    descEn: "Tunisian Minister of Economy and Planning",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B3%D9%85%D9%8A%D8%B1_%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%AD%D9%81%D9%8A%D8%B8",
    linkEn: "",
    common: "Yes",
  },
  30: {
    id: 30,
    arabicName: "المقيت",
    englishName: "Al-Muqit",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  41: {
    id: 41,
    arabicName: "الحسيب",
    englishName: "Al-Hasib",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  34: {
    id: 34,
    arabicName: "الجليل",
    englishName: "Al-Jalil",
    personAr: "عبد الجليل التميمي",
    personEn: "Abdeljelil Temimi",
    descAr: " أستاذ جامعي ومؤرخ تونسي",
    descEn: "Tunisian historian",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%AC%D9%84%D9%8A%D9%84_%D8%A7%D9%84%D8%AA%D9%85%D9%8A%D9%85%D9%8A",
    linkEn: "https://en.wikipedia.org/wiki/Abdeljelil_Temimi",
    common: "Yes",
  },
  40: {
    id: 40,
    arabicName: "الكريم",
    englishName: "Al-Karim",
    personAr: "عبد الكريم صحابو",
    personEn: "Abdelkrim Shabou",
    descAr: "ملحن و مغني تونسي",
    descEn: "Tunisian composer and singer",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%83%D8%B1%D9%8A%D9%85_%D8%B5%D8%AD%D8%A7%D8%A8%D9%88",
    linkEn: "",
    common: "Yes",
  },
  55: {
    id: 55,
    arabicName: "الرقيب",
    englishName: "Ar-Raqib",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  49: {
    id: 49,
    arabicName: "المجيب",
    englishName: "Al-Mujib",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  24: {
    id: 24,
    arabicName: "الواسع",
    englishName: "Al-Wasi'",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  31: {
    id: 31,
    arabicName: "الحكيم",
    englishName: "Al-Hakim",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  23: {
    id: 23,
    arabicName: "الودود",
    englishName: "Al-Wadud",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  36: {
    id: 36,
    arabicName: "المجيد",
    englishName: "Al-Majid",
    personAr: "عبد المجيد الشتالي",
    personEn: "Abdelmajid Chetali",
    descAr: "لاعب ومدرب كرة قدم تونسي",
    descEn: "Tunisian football coach and former player",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%85%D8%AC%D9%8A%D8%AF_%D8%A7%D9%84%D8%B4%D8%AA%D8%A7%D9%84%D9%8A",
    linkEn: "https://en.wikipedia.org/wiki/Abdelmajid_Chetali",
    common: "Yes",
  },
  51: {
    id: 51,
    arabicName: "الباعث",
    englishName: "Al-Ba'ith",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  52: {
    id: 52,
    arabicName: "الشهيد",
    englishName: "Ash-Shahid",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  53: {
    id: 53,
    arabicName: "الحق",
    englishName: "Al-Haqq",
    personAr: "عبد الحق بن صالح",
    personEn: "Abdelhak Ben Salah",
    descAr: " لاعب كرة يد تونسي",
    descEn: "Tunisian handball player",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%AD%D9%82_%D8%A8%D9%86_%D8%B5%D8%A7%D9%84%D8%AD",
    linkEn: "https://en.wikipedia.org/wiki/Abdelhak_Ben_Salah",
    common: "Yes",
  },
  33: {
    id: 33,
    arabicName: "الوكيل",
    englishName: "Al-Wakil",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  37: {
    id: 37,
    arabicName: "القوي",
    englishName: "Al-Qawiyy",
    personAr: "منال عبد القوي",
    personEn: "Manel Abdelkoui",
    descAr: "ممثلة تونسية",
    descEn: "Tunisian actress",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D9%85%D9%86%D8%A7%D9%84_%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%82%D9%88%D9%8A",
    linkEn: "https://www.imdb.com/name/nm6658948/",
    common: "Yes",
  },
  39: {
    id: 39,
    arabicName: "المتين",
    englishName: "Al-Matin",
    personAr: "عبد المتين",
    personEn: "Abdul Mateen",
    descAr: "أمير بروناي",
    descEn: "Prince of Brunei",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%85%D8%AA%D9%8A%D9%86_%D8%A3%D9%85%D9%8A%D8%B1_%D8%A8%D8%B1%D9%88%D9%86%D8%A7%D9%8A",
    linkEn: "https://en.wikipedia.org/wiki/Prince_Abdul_Mateen_of_Brunei",
    common: "Yes",
  },
  20: {
    id: 20,
    arabicName: "الولي",
    englishName: "Al-Waliyy",
    personAr: "عبد الولي الأركاني",
    personEn: "Abdul Wali Al Arkani",
    descAr: "إمام و قارئ القرآن",
    descEn: "Imam and Quran reciter ",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%88%D9%84%D9%8A_%D8%A7%D9%84%D8%A3%D8%B1%D9%83%D8%A7%D9%86%D9%8A",
    linkEn:
      "https://www.assabile.com/abdul-wali-al-arkani-92/abdul-wali-al-arkani.htm",
    common: "Yes",
  },
  54: {
    id: 54,
    arabicName: "الحميد",
    englishName: "Al-Hamid",
    personAr: "عبد الحميد بوشناق",
    personEn: "Abdelhamid Bouchnak",
    descAr: "مخرج سينمائي تونسي",
    descEn: "Tunisian filmmaker",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%AD%D9%85%D9%8A%D8%AF_%D8%A8%D9%88%D8%B4%D9%86%D8%A7%D9%82",
    linkEn: "https://en.wikipedia.org/wiki/Abdelhamid_Bouchnak",
    common: "Yes",
  },
  21: {
    id: 21,
    arabicName: "المحصي",
    englishName: "Al-Muhsi",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  32: {
    id: 32,
    arabicName: "المبدئ",
    englishName: "Al-Mubdi'",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  38: {
    id: 38,
    arabicName: "المعيد",
    englishName: "Al-Mu'id",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  22: {
    id: 22,
    arabicName: "المحيي",
    englishName: "Al-Muhyi",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  102: {
    id: 102,
    arabicName: "المميت",
    englishName: "Al-Mumit",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  68: {
    id: 68,
    arabicName: "الحي",
    englishName: "Al-Hayy",
    personAr: "عبد الحي بن سلطان",
    personEn: "Abdelhay Ben Soltane",
    descAr: "مدرب كرة قدم تونسي",
    descEn: "Tunisian football manager",
    linkAr: "",
    linkEn: "https://en.wikipedia.org/wiki/Abdelhay_Ben_Soltane",
    common: "Yes",
  },
  89: {
    id: 89,
    arabicName: "القيوم",
    englishName: "Al-Qayyum",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  90: {
    id: 90,
    arabicName: "الواجد",
    englishName: "Al-Wajid",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  100: {
    id: 100,
    arabicName: "الماجد",
    englishName: "Al-Majid",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  70: {
    id: 70,
    arabicName: "الواحد",
    englishName: "Al-Wahid",
    personAr: "عبد الواحد براهم",
    personEn: "Abdelwahed Brahem",
    descAr: "كاتب تونسي",
    descEn: "Tunisian writer",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%88%D8%A7%D8%AD%D8%AF_%D8%A8%D8%B1%D8%A7%D9%87%D9%85",
    linkEn: "https://www.ask-oracle.com/birth-chart/abdelwahed-brahem/",
    common: "Yes",
  },
  71: {
    id: 71,
    arabicName: "الصمد",
    englishName: "As-Samad",
    personAr: "عبد الصمد الكريبي",
    personEn: "Abdul Samad Al-Kuraibi",
    descAr: "مهندس ومخترع تونسي",
    descEn: "Tunisian engineer and inventor",
    linkAr: "",
    linkEn: "",
    common: "Yes",
  },
  88: {
    id: 88,
    arabicName: "القادر",
    englishName: "Al-Qadir",
    personAr: "عبد القادر الجيلاني",
    personEn: "Abdul Qadir Gilani",
    descAr: "عالم صوفي و ولي صالح",
    descEn: "Sufi scholar and a man of god",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%82%D8%A7%D8%AF%D8%B1_%D8%A7%D9%84%D8%AC%D9%8A%D9%84%D8%A7%D9%86%D9%8A",
    linkEn: "https://en.wikipedia.org/wiki/Abdul_Qadir_Gilani",
    common: "Yes",
  },
  101: {
    id: 101,
    arabicName: "المقتدر",
    englishName: "Al-Muqtadir",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  99: {
    id: 99,
    arabicName: "المقدم",
    englishName: "Al-Muqaddim",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  104: {
    id: 104,
    arabicName: "المؤخر",
    englishName: "Al-Mu'akhkhir",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  69: {
    id: 69,
    arabicName: "الأول",
    englishName: "Al-Awwal",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  105: {
    id: 105,
    arabicName: "الآخر",
    englishName: "Al-Akhir",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  75: {
    id: 75,
    arabicName: "الظاهر",
    englishName: "Az-Zahir",
    personAr: "عبد الظاهر السقا",
    personEn: "Abdel-Zaher El-Saqqa",
    descAr: "لاعب كرة قدم مصري سابق",
    descEn: "Egyptian former soccer player",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%B8%D8%A7%D9%87%D8%B1_%D8%A7%D9%84%D8%B3%D9%82%D8%A7",
    linkEn: "https://en.wikipedia.org/wiki/Abdel-Zaher_El-Saqqa",
    common: "Yes",
  },
  77: {
    id: 77,
    arabicName: "الباطن",
    englishName: "Al-Batin",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  73: {
    id: 73,
    arabicName: "الوالي",
    englishName: "Al-Wali",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  91: {
    id: 91,
    arabicName: "المتعالي",
    englishName: "Al-Muta'ali",
    personAr: "عبد المتعال الصعيدي",
    personEn: "Abdul-Muta'al Al-Sa'idi",
    descAr: "عالم لغوي",
    descEn: "Linguist",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%85%D8%AA%D8%B9%D8%A7%D9%84_%D8%A7%D9%84%D8%B5%D8%B9%D9%8A%D8%AF%D9%8A",
    linkEn: "",
    common: "Yes",
  },
  92: {
    id: 92,
    arabicName: "البر",
    englishName: "Al-Barr",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  93: {
    id: 93,
    arabicName: "التواب",
    englishName: "At-Tawwab",
    personAr: "عبد التواب يوسف",
    personEn: "Abdel Tawab Youssef",
    descAr: "مؤلف ومترجم وناشر مصري",
    descEn: "Egyptian author, translator, and publisher",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%AA%D9%88%D8%A7%D8%A8_%D9%8A%D9%88%D8%B3%D9%81",
    linkEn: "https://en.wikipedia.org/wiki/Abdul-Tawab_Yossef",
    common: "Yes",
  },
  86: {
    id: 86,
    arabicName: "المنتقم",
    englishName: "Al-Muntaqim",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  76: {
    id: 76,
    arabicName: "العفو",
    englishName: "Al-'Afuww",
    personAr: "عبد العفو بسام",
    personEn: "Abdalafo Bassam",
    descAr: "مصور وناشط فلسطيني",
    descEn: "Palestinian photographer and activist",
    linkAr: "",
    linkEn: "",
    common: "Yes",
  },
  103: {
    id: 103,
    arabicName: "الرؤوف",
    englishName: "Ar-Ra'uf",
    personAr: "عبد الرؤوف العيادي",
    personEn: "Abderraouf Ayadi",
    descAr: "ناشط حقوقي, سياسي ومحامي تونسي",
    descEn: "unisian human rights activist, politician and lawyer",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%B1%D8%A4%D9%88%D9%81_%D8%A7%D9%84%D8%B9%D9%8A%D8%A7%D8%AF%D9%8A",
    linkEn: "https://en.wikipedia.org/wiki/Abderraouf_Ayadi",
    common: "Yes",
  },
  72: {
    id: 72,
    arabicName: "مالك الملك",
    englishName: "Malik-ul-Mulk",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  106: {
    id: 106,
    arabicName: "ذو الجلال والإكرام",
    englishName: "Dhul-Jalali wal-Ikram",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  85: {
    id: 85,
    arabicName: "المقسط",
    englishName: "Al-Muqsit",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  81: {
    id: 81,
    arabicName: "الجامع",
    englishName: "Al-Jami'",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  84: {
    id: 84,
    arabicName: "الغني",
    englishName: "Al-Ghaniyy",
    personAr: "عبد الغني بن طارة",
    personEn: "Abdelghani Ben Tara",
    descAr: "ممثل تونسي",
    descEn: "Tunisian actor",
    linkAr: "https://elcinema.com/person/2125158/",
    linkEn: "https://elcinema.com/en/person/2125158/",
    common: "Yes",
  },
  95: {
    id: 95,
    arabicName: "المغني",
    englishName: "Al-Mughni",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  94: {
    id: 94,
    arabicName: "المانع",
    englishName: "Al-Mani'",
    personAr: "عبد المانع السعداوي",
    personEn: "Abdul Manea Al-Saadawi",
    descAr: "إمام وقارئ تونسي",
    descEn: "Tunisian imam and reciter",
    linkAr: "https://ar.islamway.net/scholar/4514/profile",
    linkEn: "https://en.islamway.net/recitations/scholar/4514",
    common: "Yes",
  },
  87: {
    id: 87,
    arabicName: "الضار",
    englishName: "Ad-Darr",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  80: {
    id: 80,
    arabicName: "النافع",
    englishName: "An-Nafi'",
    personAr: "عبد النافع بوراوي",
    personEn: "Abdel Nafi Bouraoui",
    descAr: "رئيس المدير العام لشركة النهوض بالمساكن الاجتماعية",
    descEn: "Chairman and CEO of the Social Housing Development Company",
    linkAr: "",
    linkEn: "",
    common: "Yes",
  },
  78: {
    id: 78,
    arabicName: "النور",
    englishName: "An-Nur",
    personAr: "أيمن عبد النور",
    personEn: "Ayman Abdennour",
    descAr: "لاعب كرة قدم تونسي سابق",
    descEn: "Former Tunisian footballer",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%A3%D9%8A%D9%85%D9%86_%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%86%D9%88%D8%B1",
    linkEn: "https://en.wikipedia.org/wiki/Aymen_Abdennour",
    common: "Yes",
  },
  74: {
    id: 74,
    arabicName: "الهادي",
    englishName: "Al-Hadi",
    personAr: "عبد الهادي بلخياط",
    personEn: "Abdelhadi Belkhayat",
    descAr: "مغني وممثل مغربي",
    descEn: "Moroccan singer and actor",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%87%D8%A7%D8%AF%D9%8A_%D8%A8%D9%84%D8%AE%D9%8A%D8%A7%D8%B7",
    linkEn: "https://en.wikipedia.org/wiki/Abdelhadi_Belkhayat",
    common: "Yes",
  },
  97: {
    id: 97,
    arabicName: "البديع",
    englishName: "Al-Badi'",
    personAr: "",
    personEn: "",
    descAr: "",
    descEn: "",
    linkAr: "",
    linkEn: "",
    common: "No",
  },
  96: {
    id: 96,
    arabicName: "الباقي",
    englishName: "Al-Baqi",
    personAr: "عبد الباقي الهرماسي",
    personEn: "Abdulbaqi Hermasi",
    descAr: "عالم اجتماع ووزير تونسي سابق",
    descEn: "Tunisian sociologist and former minister",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%A8%D8%A7%D9%82%D9%8A_%D8%A7%D9%84%D9%87%D8%B1%D9%85%D8%A7%D8%B3%D9%8A",
    linkEn: "https://en.wikipedia.org/wiki/Abdelbaki_Hermassi",
    common: "Yes",
  },
  79: {
    id: 79,
    arabicName: "الوارث",
    englishName: "Al-Warith",
    personAr: "أحمد عبد الوارث",
    personEn: "Ahmed Abdelwareth",
    descAr: "ممثل مصري",
    descEn: "Egyptian actor",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%A3%D8%AD%D9%85%D8%AF_%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%88%D8%A7%D8%B1%D8%AB",
    linkEn: "https://www.imdb.com/name/nm1000274/",
    common: "Yes",
  },
  82: {
    id: 82,
    arabicName: "الرشيد",
    englishName: "Ar-Rashid",
    personAr: "عبد الرشيد صوفي",
    personEn: "Abderrachid Soufi",
    descAr: "قارئ قرآن صومالي قطري",
    descEn: "Somali-Qatari Quran reciter",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%B1%D8%B4%D9%8A%D8%AF_%D8%B5%D9%88%D9%81%D9%8A",
    linkEn: "https://en.wikipedia.org/wiki/Abdul_Rachid_Soufi",
    common: "Yes",
  },
  83: {
    id: 83,
    arabicName: "الصبور",
    englishName: "As-Sabur",
    personAr: "صلاح عبد الصبور",
    personEn: "Salah Abdel Sabour",
    descAr: "شاعر وكاتب مسرحي مصري",
    descEn: "Egyptian poet and playwright",
    linkAr:
      "https://ar.wikipedia.org/wiki/%D8%B5%D9%84%D8%A7%D8%AD_%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%B5%D8%A8%D9%88%D8%B1",
    linkEn: "https://en.wikipedia.org/wiki/Salah_Abdel_Sabour",
    common: "Yes",
  },
};
