// Dictionary mapping name IDs to their details with personalities
export default {
  2: {
    id: 2,
    arabicName: "الله",
    englishName: "Allah'",
    personAr: "نجلاء بن عبد الله",
    personEn: "Naglaa Ben Abdallah",
    descAr: "ممثلة وعارضة أزياء تونسية",
    descEn: "Tunisian actress and model",
    link: "https://en.wikipedia.org/wiki/Naglaa_Ben_Abdallah",
  },
  13: {
    id: 13,
    arabicName: "الرحمن",
    englishName: "Ar-Rahman",
    personAr: "عبد الرحمن بن خلدون",
    personEn: "Ibn Khaldun",
    descAr: "مؤرخ عربي وأب علم الاجتماع",
    descEn: "Arab historian and father of sociology",
    link: "https://en.wikipedia.org/wiki/Ibn_Khaldun",
  },
  12: {
    id: 12,
    arabicName: "الرحيم",
    englishName: "Ar-Raheem",
    personAr: "سعاد عبد الرحيم",
    personEn: "Souad Abderrahim",
    descAr: "رئيسة بلدية تونس",
    descEn: "Mayor of Tunis",
    link: "https://en.wikipedia.org/wiki/Souad_Abderrahim",
  },
  8: {
    id: 8,
    arabicName: "الملك",
    englishName: "Al-Malik",
    personAr: "عبد الملك العريف",
    personEn: "Abdelmalek Arif",
    descAr: "رئيس العراق (١٩٦٣–١٩٦٦)",
    descEn: "President of Iraq (1963–1966)",
    link: "https://en.wikipedia.org/wiki/Abdelmalek_Arif",
  },
  11: {
    id: 11,
    arabicName: "القدوس",
    englishName: "Al-Quddus",
    personAr: "عبد القدوس السعداوي",
    personEn: "Abdelkaddous Saadaoui",
    descAr: "سياسي ورجل أعمال تونسي",
    descEn: "Tunisian politician and entrepreneur",
    link: "https://en.wikipedia.org/wiki/Abdelkaddous_Saadaoui",
  },
  10: {
    id: 10,
    arabicName: "السلام",
    englishName: "As-Salam",
    personAr: "رفيق عبد السلام",
    personEn: "Rafik Abdessalem",
    descAr: "سياسي ودبلوماسي تونسي",
    descEn: "Tunisian politician and diplomat",
    link: "https://en.wikipedia.org/wiki/Rafik_Abdessalem",
  },
  9: {
    id: 9,
    arabicName: "المؤمن",
    englishName: "Al-Mu'min",
    personAr: "سمير عبد المؤمن",
    personEn: "Samir Abdelmoumin",
    descAr: "طبيب ومسؤول صحة عامة تونسي",
    descEn: "Tunisian physician and public health official",
    link: "https://en.wikipedia.org/wiki/Samir_Abdelmoumin",
  },
  18: {
    id: 18,
    arabicName: "المهيمن",
    englishName: "Al-Muhaymin",
    personAr: "",
    personEn: "",
    descAr: "يراقب المخلوقات؛ مطّلع تماماً على جميع الأمور والأرزاق والآجال",
    descEn:
      "Watches over creatures; fully aware of all affairs, sustenance, and terms",
    link: "",
  },
  19: {
    id: 19,
    arabicName: "العزيز",
    englishName: "Al-'Aziz",
    personAr: "عبد العزيز الثعالبي",
    personEn: "Abdelaziz Thaalbi",
    descAr: "زعيم استقلال ومصلح تونسي",
    descEn: "Tunisian independence leader and reformer",
    link: "https://en.wikipedia.org/wiki/Abdelaziz_Thaalbi",
  },
  14: {
    id: 14,
    arabicName: "الجبار",
    englishName: "Al-Jabbar",
    personAr: "عبد الجبار مشوش",
    personEn: "Abdeljabar Machouch",
    descAr: "لاعب كرة قدم تونسي في الترجي الرياضي التونسي",
    descEn: "Tunisian footballer for Espérance de Tunis",
    link: "https://fr.wikipedia.org/wiki/Abdeljabar_Machouch",
  },
  15: {
    id: 15,
    arabicName: "المتكبر",
    englishName: "Al-Mutakabbir",
    personAr: "",
    personEn: "",
    descAr: "الكائن الأعظم؛ متعالٍ عن صفات الخلق",
    descEn: "Supreme Being; exalted above creation's attributes",
    link: "",
  },
  16: {
    id: 16,
    arabicName: "الخالق",
    englishName: "Al-Khaliq",
    personAr: "عبد الخالق السعداوي",
    personEn: "Abdelkhalak Saadaoui",
    descAr: "شخصية سياسية تونسية",
    descEn: "Tunisian political figure",
    link: "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%AE%D8%A7%D9%84%D9%82_%D8%A7%D9%84%D8%B3%D8%B9%D8%AF%D8%A7%D9%88%D9%8A",
  },
  17: {
    id: 17,
    arabicName: "البارئ",
    englishName: "Al-Bari'",
    personAr: "عبد الباري عطوان",
    personEn: "Abdel Bari Atwan",
    descAr: "صحفي وكاتب فلسطيني بريطاني",
    descEn: "Palestinian-British journalist and author",
    link: "https://en.wikipedia.org/wiki/Abdel_Bari_Atwan",
  },
  27: {
    id: 27,
    arabicName: "المصور",
    englishName: "Al-Musawwir",
    personAr: "",
    personEn: "",
    descAr: "يُوجد ما يشاء؛ يُصوّر المخلوقات في أشكال مختلفة",
    descEn:
      "Brings existence what He wills; shapes creatures in different forms",
    link: "",
  },
  64: {
    id: 64,
    arabicName: "الغفار",
    englishName: "Al-Ghaffar",
    personAr: "",
    personEn: "",
    descAr: "المغفرة العظيمة والدائمة للذنوب",
    descEn: "Immense and constant forgiveness of sins",
    link: "",
  },
  65: {
    id: 65,
    arabicName: "القهار",
    englishName: "Al-Qahhar",
    personAr: "",
    personEn: "",
    descAr: "يقهر كل الخلق؛ الجميع خاضعون",
    descEn: "Prevails over all creation; all submit",
    link: "",
  },
  58: {
    id: 58,
    arabicName: "الوهاب",
    englishName: "Al-Wahhab",
    personAr: "عبد الوهاب بن عياد",
    personEn: "Abdelwahab Ben Ayed",
    descAr: "رجل أعمال تونسي",
    descEn: "Tunisian businessman and entrepreneur",
    link: "https://en.wikipedia.org/wiki/Abdelwahab_Ben_Ayed",
  },
  66: {
    id: 66,
    arabicName: "الرزاق",
    englishName: "Ar-Razzaq",
    personAr: "عبد الرزاق الشّابي",
    personEn: "Abderrazak Chebbi",
    descAr: "مدرب كرة قدم ولاعب سابق تونسي",
    descEn: "Tunisian football coach and former player",
    link: "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%B1%D8%B2%D8%A7%D9%82_%D8%A7%D9%84%D8%B4%D8%A7%D8%A8%D9%8A",
  },
  67: {
    id: 67,
    arabicName: "الفتاح",
    englishName: "Al-Fattah",
    personAr: "عبد الفتاح مورو",
    personEn: "Abdelfattah Mourou",
    descAr: "سياسي تونسي ومؤسس مشارك لحركة النهضة",
    descEn: "Tunisian politician and co-founder of the Ennahda Movement",
    link: "https://en.wikipedia.org/wiki/Abdelfattah_Mourou",
  },
  63: {
    id: 63,
    arabicName: "العليم",
    englishName: "Al-'Alim",
    personAr: "الشيخ عبد العليم",
    personEn: "Sheikh Abdel Alim",
    descAr: "عالم إسلامي ومعلم قرآن",
    descEn: "Islamic scholar and Quran teacher",
    link: "",
  },
  28: {
    id: 28,
    arabicName: "القابض",
    englishName: "Al-Qabid",
    personAr: "",
    personEn: "",
    descAr: "يقبض الأرواح والأرزاق وما يشاء",
    descEn: "Takes away souls, provision, and whatsoever He pleases",
    link: "",
  },
  29: {
    id: 29,
    arabicName: "الباسط",
    englishName: "Al-Basit",
    personAr: "عبد الباسط عبد الصمد",
    personEn: "Abdel Basset Abdel Samad",
    descAr: "قارئ قرآن مصري",
    descEn: "Egyptian Quran reciter",
    link: "https://en.wikipedia.org/wiki/Abdel_Basset_Abdel_Samad",
  },
  57: {
    id: 57,
    arabicName: "الخافض",
    englishName: "Al-Khafid",
    personAr: "",
    personEn: "",
    descAr: "الذي يخفض من يشاء؛ يُذل المتكبرين والظالمين",
    descEn:
      "The One who lowers whoever He willed; abases the proud and oppressors",
    link: "",
  },
  59: {
    id: 59,
    arabicName: "الرافع",
    englishName: "Ar-Rafi'",
    personAr: "",
    personEn: "",
    descAr: "الذي يرفع من يشاء؛ يُعلي ويُعزّ المتواضعين",
    descEn:
      "The One who raises whoever He wills; elevates and exalts the humble",
    link: "",
  },
  60: {
    id: 60,
    arabicName: "المعز",
    englishName: "Al-Mu'izz",
    personAr: "",
    personEn: "",
    descAr: "مانح الشرف والقوة للعباد المطيعين المحبين",
    descEn: "The Giver of honor and strength to obedient and loving servants",
    link: "",
  },
  46: {
    id: 46,
    arabicName: "المذل",
    englishName: "Al-Mudhill",
    personAr: "",
    personEn: "",
    descAr: "المُذِل الذي يُخزي المتكبرين",
    descEn: "The Humiliator who abases the arrogant",
    link: "",
  },
  45: {
    id: 45,
    arabicName: "السميع",
    englishName: "As-Sami'",
    personAr: "",
    personEn: "",
    descAr: "يسمع جميع الأسرار دون استثناء؛ يستجيب لدعاء الداعين",
    descEn:
      "Hears all secrets without exception; answers prayers of supplicants",
    link: "",
  },
  43: {
    id: 43,
    arabicName: "البصير",
    englishName: "Al-Basir",
    personAr: "",
    personEn: "",
    descAr: "بصره يشمل كل شيء يمكن تصوّره، خفياً كان أم ظاهراً",
    descEn: "Sight encompasses everything conceivable, hidden or apparent",
    link: "",
  },
  25: {
    id: 25,
    arabicName: "الحكم",
    englishName: "Al-Hakam",
    personAr: "",
    personEn: "",
    descAr: "يحكم بعدل مطلق بناءً على المشيئة والتشريع والعدل",
    descEn:
      "Judges with absolute fairness based on will, legislation, and justice",
    link: "",
  },
  26: {
    id: 26,
    arabicName: "العدل",
    englishName: "Al-'Adl",
    personAr: "",
    personEn: "",
    descAr: "العادل الذي يُصلح الأمور بطريقة منصفة، يعطي كلاً ما يستحق",
    descEn:
      "The Just who rectifies matters in equitable manner, giving each what they deserve",
    link: "",
  },
  61: {
    id: 61,
    arabicName: "اللطيف",
    englishName: "Al-Latif",
    personAr: "عبد اللطيف المكي",
    personEn: "Abdellatif Mekki",
    descAr: "سياسي تونسي ووزير صحة سابق",
    descEn: "Tunisian politician and former Minister of Health",
    link: "https://en.wikipedia.org/wiki/Abdellatif_Mekki",
  },
  47: {
    id: 47,
    arabicName: "الخبير",
    englishName: "Al-Khabir",
    personAr: "",
    personEn: "",
    descAr: "مطّلع تماماً على الأمور الظاهرة والخفية والأكثر خفاءً",
    descEn: "Fully aware of apparent, hidden, and most concealed matters",
    link: "",
  },
  56: {
    id: 56,
    arabicName: "الحليم",
    englishName: "Al-Halim",
    personAr: "عبد الحليم حافظ",
    personEn: "Abdel Halim Hafez",
    descAr: "مغني وممثل مصري",
    descEn: "Egyptian singer and actor",
    link: "https://en.wikipedia.org/wiki/Abdel_Halim_Hafez",
  },
  44: {
    id: 44,
    arabicName: "العظيم",
    englishName: "Al-'Azim",
    personAr: "",
    personEn: "",
    descAr: "يشمل كل العظمة والجلال والمجد في الذات والصفات",
    descEn:
      "Comprises all greatness, majesty, and glory in being and attributes",
    link: "",
  },
  42: {
    id: 42,
    arabicName: "الغفور",
    englishName: "Al-Ghafur",
    personAr: "",
    personEn: "",
    descAr: "يغفر الذنوب؛ يقبل التوبة؛ يستر الذنوب؛ يُظهر الرحمة اللامتناهية",
    descEn:
      "Forgives sins; accepts repentance; conceals sins; shows endless compassion",
    link: "",
  },
  62: {
    id: 62,
    arabicName: "الشكور",
    englishName: "Ash-Shakur",
    personAr: "",
    personEn: "",
    descAr: "يرضى بالشكر القليل؛ يُكافئ على الطاعة",
    descEn: "Pleased with little gratitude; rewarding for obedience",
    link: "",
  },
  35: {
    id: 35,
    arabicName: "العلي",
    englishName: "Al-'Aliyy",
    personAr: "",
    personEn: "",
    descAr: "العلو المطلق في الذات والمكانة والصفات والسيطرة",
    descEn: "Absolute highness in Being, position, attributes, and dominance",
    link: "",
  },
  50: {
    id: 50,
    arabicName: "الكبير",
    englishName: "Al-Kabir",
    personAr: "",
    personEn: "",
    descAr: "العظيم السامي؛ لا يوجد ما هو أعظم",
    descEn: "Magnificent and Sublime; nothing greater exists",
    link: "",
  },
  48: {
    id: 48,
    arabicName: "الحفيظ",
    englishName: "Al-Hafiz",
    personAr: "سمير عبد الحفيظ",
    personEn: "Samir Abdelhafid",
    descAr: "وزير الاقتصاد والتخطيط التونسي",
    descEn: "Tunisian Minister of Economy and Planning",
    link: "https://ar.wikipedia.org/wiki/%D8%B3%D9%85%D9%8A%D8%B1_%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%AD%D9%81%D9%8A%D8%B8",
  },
  30: {
    id: 30,
    arabicName: "المقيت",
    englishName: "Al-Muqit",
    personAr: "",
    personEn: "",
    descAr: "له القدرة على كل شيء؛ يرزق؛ يحفظ بعطاياه",
    descEn:
      "Has power over all things; provides sustenance; preserves with His grants",
    link: "",
  },
  41: {
    id: 41,
    arabicName: "الحسيب",
    englishName: "Al-Hasib",
    personAr: "",
    personEn: "",
    descAr: "كافٍ لمن يتوكل عليه؛ عالم بالعباد؛ يُحاسب على الأعمال",
    descEn:
      "Sufficient for those who rely; aware of slaves; takes account of actions",
    link: "",
  },
  34: {
    id: 34,
    arabicName: "الجليل",
    englishName: "Al-Jalil",
    personAr: "",
    personEn: "",
    descAr: "الجليل؛ العظيم فوق الجميع في الكرامة والمرتبة والعظمة المهيبة",
    descEn:
      "The Majestic; great one above all in dignity, rank, and awe-inspiring greatness",
    link: "",
  },
  40: {
    id: 40,
    arabicName: "الكريم",
    englishName: "Al-Karim",
    personAr: "",
    personEn: "",
    descAr: "يُعطي بسخاء وينفع بلا حدود؛ يمنح قبل الاستحقاق",
    descEn:
      "Gives abundantly and benefits immeasurably; bestows before deserving",
    link: "",
  },
  55: {
    id: 55,
    arabicName: "الرقيب",
    englishName: "Ar-Raqib",
    personAr: "",
    personEn: "",
    descAr: "السمع والبصر والعلم تشمل كل شيء",
    descEn: "Hearing, seeing, and knowledge encompass everything",
    link: "",
  },
  49: {
    id: 49,
    arabicName: "المجيب",
    englishName: "Al-Mujib",
    personAr: "",
    personEn: "",
    descAr: "يستجيب للدعاء بفضل؛ يُلبّي الطلبات",
    descEn: "Favorably responds to supplications; answers requests",
    link: "",
  },
  24: {
    id: 24,
    arabicName: "الواسع",
    englishName: "Al-Wasi'",
    personAr: "",
    personEn: "",
    descAr: "يشمل كل شيء بالرحمة والعلم؛ الرزق يصل إلى الجميع",
    descEn:
      "Embraces everything in mercy and knowledge; sustenance reaches all",
    link: "",
  },
  31: {
    id: 31,
    arabicName: "الحكيم",
    englishName: "Al-Hakim",
    personAr: "",
    personEn: "",
    descAr: "الحكمة العليا في جميع الأقدار والتشريع والحكم",
    descEn: "Supreme wisdom in all decrees, legislation, and judgment",
    link: "",
  },
  23: {
    id: 23,
    arabicName: "الودود",
    englishName: "Al-Wadud",
    personAr: "",
    personEn: "",
    descAr: "يُحب الأنبياء والرسل والعباد المطيعين؛ الأحب الجدير بالمحبة",
    descEn:
      "Loves prophets, messengers, and obedient servants; most beloved deserving love",
    link: "",
  },
  36: {
    id: 36,
    arabicName: "المجيد",
    englishName: "Al-Majid",
    personAr: "",
    personEn: "",
    descAr: "الصفات الكاملة؛ الأفعال العظيمة؛ الكرم اللامحدود",
    descEn: "Perfect attributes; greatest actions; boundless generosity",
    link: "",
  },
  51: {
    id: 51,
    arabicName: "الباعث",
    englishName: "Al-Ba'ith",
    personAr: "",
    personEn: "",
    descAr: "الباعث الذي يبعث جميع الخلائق للحساب في الآخرة",
    descEn:
      "The Resurrector who raises all beings to judgment in the afterlife",
    link: "",
  },
  52: {
    id: 52,
    arabicName: "الشهيد",
    englishName: "Ash-Shahid",
    personAr: "",
    personEn: "",
    descAr: "مطّلع على كل شيء بالتفصيل؛ لا شيء يخفى عليه",
    descEn: "Aware of everything in detail; nothing hidden from Him",
    link: "",
  },
  53: {
    id: 53,
    arabicName: "الحق",
    englishName: "Al-Haqq",
    personAr: "",
    personEn: "",
    descAr: "موجود حقاً؛ كلامه وقضاؤه وتشريعه صادق مطلقاً",
    descEn:
      "Truly exists; His speech, decree, and legislation are absolutely truthful",
    link: "",
  },
  33: {
    id: 33,
    arabicName: "الوكيل",
    englishName: "Al-Wakil",
    personAr: "",
    personEn: "",
    descAr: "يُدبّر أمور جميع المخلوقات؛ يرزق؛ يُلبّي الحاجات؛ يحمي الصالحين",
    descEn:
      "Disposes all creatures' affairs; provides; fulfills needs; protects righteous",
    link: "",
  },
  37: {
    id: 37,
    arabicName: "القوي",
    englishName: "Al-Qawiyy",
    personAr: "",
    personEn: "",
    descAr: "القدرة الكاملة؛ الأوامر مُنفّذة؛ القضاء لا يُرد",
    descEn: "Perfect power; commands executed; decree never averted",
    link: "",
  },
  39: {
    id: 39,
    arabicName: "المتين",
    englishName: "Al-Matin",
    personAr: "",
    personEn: "",
    descAr: "القوة والقدرة المطلقة؛ لا يتعرض لمشقة أو تعب",
    descEn: "Ultimate strength and ability; endures no hardship or weariness",
    link: "",
  },
  20: {
    id: 20,
    arabicName: "الولي",
    englishName: "Al-Waliyy",
    personAr: "",
    personEn: "",
    descAr: "الولي المدبّر لكل شيء؛ الخالق والحاكم المستحق للعبادة",
    descEn: "Guardian managing all; Creator and Ruler deserving worship",
    link: "",
  },
  54: {
    id: 54,
    arabicName: "الحميد",
    englishName: "Al-Hamid",
    personAr: "عبد الحميد بوشناق",
    personEn: "Abdelhamid Bouchnak",
    descAr: "مخرج سينمائي تونسي، ابن لطفي بوشناق",
    descEn: "Tunisian filmmaker, son of Lotfi Bouchnak",
    link: "https://en.wikipedia.org/wiki/Abdelhamid_Bouchnak",
  },
  21: {
    id: 21,
    arabicName: "المحصي",
    englishName: "Al-Muhsi",
    personAr: "",
    personEn: "",
    descAr: "المُحصي بحساب كامل؛ يحفظ سجلاً تاماً لجميع الأعمال",
    descEn:
      "The Reckoner with perfect accounting; keeps complete record of all deeds",
    link: "",
  },
  32: {
    id: 32,
    arabicName: "المبدئ",
    englishName: "Al-Mubdi'",
    personAr: "",
    personEn: "",
    descAr: "مُبدئ كل الخلق؛ بادئ كل شيء من العدم",
    descEn:
      "The Originator of all creation; beginner of all things from nothing",
    link: "",
  },
  38: {
    id: 38,
    arabicName: "المعيد",
    englishName: "Al-Mu'id",
    personAr: "",
    personEn: "",
    descAr: "المُعيد الذي يُرجع ويُجدّد؛ يمنح حياة جديدة بعد الموت",
    descEn:
      "The Restorer who brings back and regenerates; gives new life after death",
    link: "",
  },
  22: {
    id: 22,
    arabicName: "المحيي",
    englishName: "Al-Muhyi",
    personAr: "",
    personEn: "",
    descAr: "واهب الحياة الذي يخلق الحي من الميت ويُحيي القلوب بالعلم",
    descEn:
      "The Giver of Life who creates living from lifeless and revives hearts with knowledge",
    link: "",
  },
  102: {
    id: 102,
    arabicName: "المميت",
    englishName: "Al-Mumit",
    personAr: "",
    personEn: "",
    descAr: "مُسبّب الموت الذي يُميت الأحياء",
    descEn: "The Causer of Death who renders the living dead",
    link: "",
  },
  68: {
    id: 68,
    arabicName: "الحي",
    englishName: "Al-Hayy",
    personAr: "",
    personEn: "",
    descAr:
      "الحياة الكاملة الأبدية التي تستلزم جميع الصفات الكاملة وتنفي النقائص",
    descEn:
      "Perfect, eternal life requiring all perfect attributes and negating imperfections",
    link: "",
  },
  89: {
    id: 89,
    arabicName: "القيوم",
    englishName: "Al-Qayyum",
    personAr: "",
    personEn: "",
    descAr: "السيد المكتفي بذاته الذي يعتمد عليه كل الوجود",
    descEn: "Self-sufficient Master on whom all existence depends",
    link: "",
  },
  90: {
    id: 90,
    arabicName: "الواجد",
    englishName: "Al-Wajid",
    personAr: "عبد الواحد المكني",
    personEn: "Abdelwahed Mokni",
    descAr: "مؤرخ وأستاذ جامعي تونسي",
    descEn: "Tunisian historian and university professor",
    link: "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%88%D8%A7%D8%AD%D8%AF_%D8%A7%D9%84%D9%85%D9%83%D9%86%D9%8A",
  },
  100: {
    id: 100,
    arabicName: "الماجد",
    englishName: "Al-Majid",
    personAr: "",
    personEn: "",
    descAr: "الصفات الكاملة؛ الأفعال العظيمة؛ الكرم اللامحدود",
    descEn: "Perfect attributes; greatest actions; boundless generosity",
    link: "",
  },
  70: {
    id: 70,
    arabicName: "الواحد",
    englishName: "Al-Wahid",
    personAr: "",
    personEn: "",
    descAr: "فريد بلا شركاء، واحد في الذات والصفات والأفعال والربوبية",
    descEn:
      "Unique without partners, one in being, attributes, actions, and lordship",
    link: "",
  },
  71: {
    id: 71,
    arabicName: "الصمد",
    englishName: "As-Samad",
    personAr: "عبد الباسط عبد الصمد",
    personEn: "Abdel Basset Abdel Samad",
    descAr: "قارئ قرآن مصري",
    descEn: "Egyptian Quran reciter",
    link: "https://en.wikipedia.org/wiki/Abdel_Basset_Abdel_Samad",
  },
  88: {
    id: 88,
    arabicName: "القادر",
    englishName: "Al-Qadir",
    personAr: "عبد القادر الجيلاني",
    personEn: "Abdul Qadir Gilani",
    descAr: "عالم صوفي ومتصوف فارسي",
    descEn: "Persian Sufi scholar and saint",
    link: "https://en.wikipedia.org/wiki/Abdul_Qadir_Gilani",
  },
  101: {
    id: 101,
    arabicName: "المقتدر",
    englishName: "Al-Muqtadir",
    personAr: "",
    personEn: "",
    descAr: "صيغة مبالغة تؤكد القدرة الكاملة",
    descEn: "Intensive form stressing perfect ability",
    link: "",
  },
  99: {
    id: 99,
    arabicName: "المقدم",
    englishName: "Al-Muqaddim",
    personAr: "",
    personEn: "",
    descAr: "يضع الأشياء في مواضعها؛ يُقدّم ما يشاء",
    descEn: "Places things where they belong; advances what He wills",
    link: "",
  },
  104: {
    id: 104,
    arabicName: "المؤخر",
    englishName: "Al-Mu'akhkhir",
    personAr: "",
    personEn: "",
    descAr: "يُؤخّر ما يشاء؛ يُمهل ما يشاء بحكمة وعدل",
    descEn:
      "Postpones what He wills; delays what He pleases in wisdom and justice",
    link: "",
  },
  69: {
    id: 69,
    arabicName: "الأول",
    englishName: "Al-Awwal",
    personAr: "",
    personEn: "",
    descAr: "لا شيء كان قبله؛ خلق كل شيء من العدم المطلق",
    descEn: "Nothing existed before Him; He created all from absolute nothing",
    link: "",
  },
  105: {
    id: 105,
    arabicName: "الآخر",
    englishName: "Al-Akhir",
    personAr: "",
    personEn: "",
    descAr: "لا شيء يأتي بعده؛ يوجد إلى الأبد اللامتناهي",
    descEn: "Nothing comes after Him; He exists infinitely for all eternity",
    link: "",
  },
  75: {
    id: 75,
    arabicName: "الظاهر",
    englishName: "Az-Zahir",
    personAr: "",
    personEn: "",
    descAr: "الأعظم، فوق كل شيء ولا شيء فوقه",
    descEn: "Most Great, above everything with nothing above Him",
    link: "",
  },
  77: {
    id: 77,
    arabicName: "الباطن",
    englishName: "Al-Batin",
    personAr: "",
    personEn: "",
    descAr: "الأقرب من كل شيء بسبب الاطّلاع التام على الأسرار والأمور الخفية",
    descEn:
      "Nearest to everything due to full awareness of secrets and hidden matters",
    link: "",
  },
  73: {
    id: 73,
    arabicName: "الوالي",
    englishName: "Al-Wali",
    personAr: "",
    personEn: "",
    descAr: "الوالي والحامي؛ حافظ كل الخلق",
    descEn: "The Governor and Protector; guardian of all creation",
    link: "",
  },
  91: {
    id: 91,
    arabicName: "المتعالي",
    englishName: "Al-Muta'ali",
    personAr: "",
    personEn: "",
    descAr: "المتعالي؛ العالي السامي المتجاوز لكل الخلق",
    descEn:
      "The Most High; supremely elevated and transcendent above all creation",
    link: "",
  },
  92: {
    id: 92,
    arabicName: "البر",
    englishName: "Al-Barr",
    personAr: "",
    personEn: "",
    descAr: "يُمطر النعم الظاهرة والخفية؛ يُضاعف الثواب؛ يغفر للمخطئين",
    descEn:
      "Showers apparent and hidden blessings; multiplies rewards; forgives wrongdoers",
    link: "",
  },
  93: {
    id: 93,
    arabicName: "التواب",
    englishName: "At-Tawwab",
    personAr: "",
    personEn: "",
    descAr: "يُعين العباد على التوبة؛ يقبل التوبة ويعفو عن الذنوب",
    descEn: "Helps servants repent; accepts repentance and pardons sins",
    link: "",
  },
  86: {
    id: 86,
    arabicName: "المنتقم",
    englishName: "Al-Muntaqim",
    personAr: "",
    personEn: "",
    descAr: "المنتقم الذي يُعاقب الظالمين بعدل",
    descEn: "The Avenger who justly punishes wrongdoers",
    link: "",
  },
  76: {
    id: 76,
    arabicName: "العفو",
    englishName: "Al-'Afuww",
    personAr: "",
    personEn: "",
    descAr: "يعفو ويتجاوز عن الذنوب؛ يمنح العفو الذي يمحو كل الخطايا",
    descEn: "Forgives and overlooks wrongdoing; grants pardon erasing all sins",
    link: "",
  },
  103: {
    id: 103,
    arabicName: "الرؤوف",
    englishName: "Ar-Ra'uf",
    personAr: "",
    personEn: "",
    descAr: "يمنح أعلى أشكال الرحمة للخلق في الدنيا والآخرة",
    descEn: "Bestows highest form of mercy to creation in world and hereafter",
    link: "",
  },
  72: {
    id: 72,
    arabicName: "مالك الملك",
    englishName: "Malik-ul-Mulk",
    personAr: "",
    personEn: "",
    descAr: "مالك الملك؛ المالك الوحيد لكل السيادة بسلطة مطلقة",
    descEn:
      "The Owner of Sovereignty; sole possessor of all dominion with absolute authority",
    link: "",
  },
  106: {
    id: 106,
    arabicName: "ذو الجلال والإكرام",
    englishName: "Dhul-Jalali wal-Ikram",
    personAr: "",
    personEn: "",
    descAr: "ذو الجلال والإكرام؛ صاحب المجد والكرم",
    descEn: "The Possessor of Majesty and Honor; Owner of Glory and Generosity",
    link: "",
  },
  85: {
    id: 85,
    arabicName: "المقسط",
    englishName: "Al-Muqsit",
    personAr: "",
    personEn: "",
    descAr: "العادل الذي هو الأكثر إنصافاً ويُكافئ أي خير بما يفوق الحد",
    descEn: "The Just One who is most fair and rewards any good beyond measure",
    link: "",
  },
  81: {
    id: 81,
    arabicName: "الجامع",
    englishName: "Al-Jami'",
    personAr: "",
    personEn: "",
    descAr: "الجامع الذي يوحّد؛ يجمع الأشياء المتفرقة ويحشر الخلق للحساب",
    descEn:
      "The Gatherer who unites; brings together scattered things and gathers creation for judgment",
    link: "",
  },
  84: {
    id: 84,
    arabicName: "الغني",
    englishName: "Al-Ghaniyy",
    personAr: "عبد الغني بن طارة",
    personEn: "Abdelghani Ben Taraا",
    descAr: "ممثل تونسي",
    descEn: "Tunisian actor",
    link: "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%BA%D9%86%D9%8A_%D8%A8%D9%86_%D8%B7%D8%A7%D8%B1%D8%A9",
  },
  95: {
    id: 95,
    arabicName: "المغني",
    englishName: "Al-Mughni",
    personAr: "",
    personEn: "",
    descAr: "المُغني الذي يمنح الغنى المادي والروحي لمن يشاء",
    descEn:
      "The Enricher who grants wealth and spiritual richness to whomever He wills",
    link: "",
  },
  94: {
    id: 94,
    arabicName: "المانع",
    englishName: "Al-Mani'",
    personAr: "",
    personEn: "",
    descAr: "المانع الذي يمنع الضرر أو يمسك الرزق بحكمته",
    descEn:
      "The Withholder who prevents harm or withholds provision in His wisdom",
    link: "",
  },
  87: {
    id: 87,
    arabicName: "الضار",
    englishName: "Ad-Darr",
    personAr: "",
    personEn: "",
    descAr: "الضار الذي يسمح بالضرر أو المشقة اختباراً أو عدلاً",
    descEn: "The Distresser who allows harm or difficulty as test or justice",
    link: "",
  },
  80: {
    id: 80,
    arabicName: "النافع",
    englishName: "An-Nafi'",
    personAr: "",
    personEn: "",
    descAr: "النافع الذي يمنح المنفعة والخير والبركة",
    descEn: "The Propitious who grants benefit, good, and blessing",
    link: "",
  },
  78: {
    id: 78,
    arabicName: "النور",
    englishName: "An-Nur",
    personAr: "أيمن عبد النور",
    personEn: "Ayman Abdennour",
    descAr: "لاعب كرة قدم تونسي",
    descEn: "Tunisian footballer",
    link: "https://en.wikipedia.org/wiki/Ayman_Abdennour",
  },
  74: {
    id: 74,
    arabicName: "الهادي",
    englishName: "Al-Hadi",
    personAr: "عبد الهادي بلخياط",
    personEn: "Abdelhadi Belkhayat",
    descAr: "مغني وممثل مغربي",
    descEn: "Moroccan singer and actor",
    link: "https://en.wikipedia.org/wiki/Abdelhadi_Belkhayat",
  },
  97: {
    id: 97,
    arabicName: "البديع",
    englishName: "Al-Badi'",
    personAr: "",
    personEn: "",
    descAr: "المُبدع الذي لا مثيل له؛ خلق الكون دون سابقة أو مثال",
    descEn:
      "The Incomparable Originator; created universe without precedent or example",
    link: "",
  },
  96: {
    id: 96,
    arabicName: "الباقي",
    englishName: "Al-Baqi",
    personAr: "عبد الباقي الهرماسي",
    personEn: "Abdulbaqi Hermasi",
    descAr: "عالم اجتماع ووزير تونسي سابق",
    descEn: "Tunisian sociologist and former minister",
    link: "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%A8%D8%A7%D9%82%D9%8A_%D8%A7%D9%84%D9%87%D8%B1%D9%85%D8%A7%D8%B3%D9%8A",
  },
  79: {
    id: 79,
    arabicName: "الوارث",
    englishName: "Al-Warith",
    personAr: "أحمد عبد الوارث",
    personEn: "Ahmed Abdelwareth",
    descAr: "ممثل مصري",
    descEn: "Egyptian actor",
    link: "https://ar.wikipedia.org/wiki/%D8%A3%D8%AD%D9%85%D8%AF_%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D9%88%D8%A7%D8%B1%D8%AB",
  },
  82: {
    id: 82,
    arabicName: "الرشيد",
    englishName: "Ar-Rashid",
    personAr: "عبد الرشيد صوفي",
    personEn: "Abderrachid Soufi",
    descAr: "قارئ قرآن صومالي قطري",
    descEn: "Somali-Qatari Quran reciter",
    link: "https://ar.wikipedia.org/wiki/%D8%B9%D8%A8%D8%AF_%D8%A7%D9%84%D8%B1%D8%B4%D9%8A%D8%AF_%D8%B5%D9%88%D9%81%D9%8A",
  },
  83: {
    id: 83,
    arabicName: "الصبور",
    englishName: "As-Sabur",
    personAr: "صلاح عبد الصبور",
    personEn: "Salah Abdel Sabour",
    descAr: "شاعر وكاتب مسرحي مصري",
    descEn: "Egyptian poet and playwright",
    link: "https://en.wikipedia.org/wiki/Salah_Abdel_Sabour",
  },
};
