export default [
  {
    logo: "../src/NBALogo/Atlanta.png",
    id: "1",
    disable: false,
    name: "Atlanta Hawks",
    arena: "State Farm Arena",
    date: "08/23/22",
    opp: "Hornets",
    alt: "State Farm Arena Picture",
    path: "../src/NBALogo/hawks.jpg",
  },
  {
    logo: "../src/NBALogo/Celtics.png",
    disable: true,
    id: "2",
    alt: "Lapland winter scene",
    path: "25507134@N00/6527537485",
  },
  {
    logo: "../src/NBALogo/Nets.png",
    disable: false,
    id: "3",
    alt: "Jellyfish",
    path: "../src/NBALogo/nets.jpg",
  },
  {
    logo: "../src/NBALogo/Hornets.png",
    disable: true,
    id: "4",
    alt: "A man scuba diving",
    path: "32751486@N00/4608886209",
  },
  {
    logo: "../src/NBALogo/Bulls.png",
    disable: false,
    id: "5",
    alt: "Underwater scene",
    path: "../src/NBALogo/bull.jpg",
  },
  {
    logo: "../src/NBALogo/Cavaliers.png",
    disable: false,
    id: "6",
    alt: "Ferns",
    path: "../src/NBALogo/clev.jpg",
  },
  {
    logo: "../src/NBALogo/Detroit.png",
    disable: false,
    id: "7",
    alt: "Posters in a bar",
    path: "../src/NBALogo/pis.jpg",
  },
  {
    logo: "../src/NBALogo/Pacers.png",
    disable: false,
    id: "8",
    alt: "Daffodil",
    path: "../src/NBALogo/pace.jpg",
  },
  {
    logo: "../src/NBALogo/Heat.png",
    disable: true,
    id: "9",
    alt: "Dust storm in Sydney",
    path: "56068058@N00/3945496657",
  },
  {
    logo: "../src/NBALogo/Bucks.png",
    disable: false,
    id: "10",
    alt: "Postbox",
    path: "../src/NBALogo/buck.jpg",
  },
  {
    logo: "../src/NBALogo/Knicks.png",
    disable: true,
    id: "11",
    alt: "Fireworks",
    path: "8484971@N07/2625506561",
  },
  {
    logo: "../src/NBALogo/Magic.png",
    disable: true,
    id: "12",
    alt: "The Stereophonics",
    path: "58028312@N00/5385464371",
  },
  {
    logo: "../src/NBALogo/Sixers.png",
    disable: true,
    id: "13",
    alt: "The Stereophonffics",
    path: "43428526@N03/7863279376",
  },
  {
    logo: "../src/NBALogo/Raptors.png",
    disable: true,
    id: "14",
    alt: "The Stffereophonics",
    path: "43428526@N03/7863279376",
  },
  {
    logo: "../src/NBALogo/Wizards.png",
    disable: false,
    id: "15",
    alt: "Daffodil",
    path: "../src/NBALogo/wiz.jpg",
  },
];
