export default [
  {
    logo: "../src/NBALogo/Dallas.png",
    id: "1",
    disable: true,
    alt: "Crepuscular rays",
    path: "../src/NBALogo/hawks.jpg",
  },
  {
    logo: "../src/NBALogo/Denver.png",
    disable: true,
    id: "2",
    alt: "Lapland winter scene",
    path: "25507134@N00/6527537485",
  },
  {
    logo: "../src/NBALogo/Golden.png",
    disable: true,
    id: "3",
    alt: "Jellyfish",
    path: "37707866@N00/3354331318",
  },
  {
    logo: "../src/NBALogo/Rockets.png",
    disable: true,
    id: "4",
    alt: "A man scuba diving",
    path: "32751486@N00/4608886209",
  },
  {
    logo: "../src/NBALogo/Clip.png",
    disable: true,
    id: "5",
    alt: "Underwater scene",
    path: "25483059@N08/5548569010",
  },
  {
    logo: "../src/NBALogo/Lakers.png",
    disable: true,
    id: "6",
    alt: "Ferns",
    path: "../src/NBALogo/clev.jpg",
  },
  {
    logo: "../src/NBALogo/Memphis.png",
    disable: true,
    id: "7",
    alt: "Posters in a bar",
    path: "../src/NBALogo/pis.jpg",
  },
  {
    logo: "../src/NBALogo/Timber.png",
    disable: true,
    id: "8",
    alt: "Daffodil",
    path: "../src/NBALogo/pace.jpg",
  },
  {
    logo: "../src/NBALogo/Pelicans.png",
    disable: false,
    id: "9",
    alt: "Dust storm in Sydney",
    path: "../src/NBALogo/peli.jpg",
  },
  {
    logo: "../src/NBALogo/Thunder.png",
    disable: true,
    id: "10",
    alt: "Postbox",
    path: "31883499@N05/4216820032",
  },
  {
    logo: "../src/NBALogo/Suns.png",
    disable: true,
    id: "11",
    alt: "Fireworks",
    path: "8484971@N07/2625506561",
  },
  {
    logo: "../src/NBALogo/Portland.png",
    disable: true,
    id: "12",
    alt: "The Stereophonics",
    path: "58028312@N00/5385464371",
  },
  {
    logo: "../src/NBALogo/Kings.png",
    disable: true,
    id: "13",
    alt: "The Stereophonffics",
    path: "43428526@N03/7863279376",
  },
  {
    logo: "../src/NBALogo/Spurs.png",
    disable: true,
    id: "14",
    alt: "The Stffereophonics",
    path: "43428526@N03/7863279376",
  },
  {
    logo: "../src/NBALogo/Jazz.png",
    disable: true,
    id: "15",
    alt: "Daffodil",
    path: "../src/NBALogo/wiz.jpg",
  },
];
